package de.xjanx05.xjavaapi.mc.spigot;

import java.util.Arrays;
import java.util.HashMap;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

public enum Materials {
    ACACIA_BOAT("ACACIA_BOAT", 0, new String[]{"BOAT_ACACIA"}),
    ACACIA_BUTTON("ACACIA_BUTTON", 0, new String[]{"WOOD_BUTTON"}),
    ACACIA_DOOR("ACACIA_DOOR", 0, new String[]{"ACACIA_DOOR", "ACACIA_DOOR_ITEM"}),
    ACACIA_FENCE("ACACIA_FENCE", 0, new String[]{"ACACIA_FENCE"}),
    ACACIA_FENCE_GATE("ACACIA_FENCE_GATE", 0, new String[]{"ACACIA_FENCE_GATE"}),
    ACACIA_LEAVES("ACACIA_LEAVES", 0, new String[]{"LEAVES_2"}),
    ACACIA_LOG("ACACIA_LOG", 0, new String[]{"LOG_2"}),
    ACACIA_PLANKS("ACACIA_PLANKS", 4, new String[]{"WOOD"}),
    ACACIA_PRESSURE_PLATE("ACACIA_PRESSURE_PLATE", 0, new String[]{"WOOD_PLATE"}),
    ACACIA_SAPLING("ACACIA_SAPLING", 4, new String[]{"SAPLING"}),
    ACACIA_SLAB("ACACIA_SLAB", 4, new String[]{"WOODEN_SLAB", "WOOD_STEP", "WOOD_DOUBLE_STEP"}),
    ACACIA_STAIRS("ACACIA_STAIRS", 4, new String[]{"ACACIA_STAIRS"}),
    ACACIA_TRAPDOOR("ACACIA_TRAPDOOR", 0, new String[]{"TRAP_DOOR"}),
    ACACIA_WOOD("ACACIA_WOOD", 0, new String[]{"LOG_2"}),
    ACTIVATOR_RAIL("ACTIVATOR_RAIL", 0, new String[]{"ACTIVATOR_RAIL"}),
    AIR("AIR", 0, new String[]{"AIR"}),
    ALLIUM("ALLIUM", 2, new String[]{"RED_ROSE"}),
    ANDESITE("ANDESITE", 5, new String[]{"STONE"}),
    ANVIL("ANVIL", 0, new String[]{"ANVIL"}),
    APPLE("APPLE", 0, new String[]{"APPLE"}),
    ARMOR_STAND("ARMOR_STAND", 0, new String[]{"ARMOR_STAND"}),
    ARROW("ARROW", 0, new String[]{"ARROW"}),
    ATTACHED_MELON_STEM("ATTACHED_MELON_STEM", 7, new String[]{"MELON_STEM"}),
    ATTACHED_PUMPKIN_STEM("ATTACHED_PUMPKIN_STEM", 7, new String[]{"PUMPKIN_STEM"}),
    AZURE_BLUET("AZURE_BLUET", 3, new String[]{"RED_ROSE"}),
    BAKED_POTATO("BAKED_POTATO", 0, new String[]{"BAKED_POTATO"}),
    BARRIER("BARRIER", 0, new String[]{"BARRIER"}),
    BAT_SPAWN_EGG("BAT_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    BEACON("BEACON", 0, new String[]{"BEACON"}),
    BEDROCK("BEDROCK", 0, new String[]{"BEDROCK"}),
    BEEF("BEEF", 0, new String[]{"RAW_BEEF"}),
    BEETROOT("BEETROOT", 0, new String[]{"BEETROOT"}),
    BEETROOT_SEEDS("BEETROOT_SEEDS", 0, new String[]{"BEETROOT_SEEDS"}),
    BEETROOT_SOUP("BEETROOT_SOUP", 0, new String[]{"BEETROOT_SOUP"}),
    BEETROOTS("BEETROOTS", 0, new String[]{"BEETROOT", "BEETROOT_BLOCK"}),
    BIRCH_BOAT("BIRCH_BOAT", 0, new String[]{"BOAT_BIRCH"}),
    BIRCH_BUTTON("BIRCH_BUTTON", 0, new String[]{"WOOD_BUTTON"}),
    BIRCH_DOOR("BIRCH_DOOR", 0, new String[]{"BIRCH_DOOR", "BIRCH_DOOR_ITEM"}),
    BIRCH_FENCE("BIRCH_FENCE", 0, new String[]{"BIRCH_FENCE"}),
    BIRCH_FENCE_GATE("BIRCH_FENCE_GATE", 0, new String[]{"BIRCH_FENCE_GATE"}),
    BIRCH_LEAVES("BIRCH_LEAVES", 2, new String[]{"LEAVES"}),
    BIRCH_LOG("BIRCH_LOG", 2, new String[]{"LOG"}),
    BIRCH_PLANKS("BIRCH_PLANKS", 2, new String[]{"WOOD"}),
    BIRCH_PRESSURE_PLATE("BIRCH_PRESSURE_PLATE", 0, new String[]{"WOOD_PLATE"}),
    BIRCH_SAPLING("BIRCH_SAPLING", 2, new String[]{"SAPLING"}),
    BIRCH_SLAB("BIRCH_SLAB", 2, new String[]{"WOODEN_SLAB", "WOOD_STEP", "WOOD_DOUBLE_STEP"}),
    BIRCH_STAIRS("BIRCH_STAIRS", 0, new String[]{"BIRCH_WOOD_STAIRS"}),
    BIRCH_TRAPDOOR("BIRCH_TRAPDOOR", 0, new String[]{"TRAP_DOOR"}),
    BIRCH_WOOD("BIRCH_WOOD", 2, new String[]{"LOG"}),
    BLACK_BANNER("BLACK_BANNER", 0, new String[]{"BANNER", "STANDING_BANNER"}),
    BLACK_BED("BLACK_BED", 15, new String[]{"BED", "BED_BLOCK"}),
    BLACK_CARPET("BLACK_CARPET", 15, new String[]{"CARPET"}),
    BLACK_CONCRETE("BLACK_CONCRETE", 15, new String[]{"CONCRETE"}),
    BLACK_CONCRETE_POWDER("BLACK_CONCRETE_POWDER", 15, new String[]{"CONCRETE_POWDER"}),
    BLACK_DYE("BLACK_DYE", 0, new String[]{"INK_SACK"}),
    BLACK_GLAZED_TERRACOTTA("BLACK_GLAZED_TERRACOTTA", 0, new String[]{"BLACK_GLAZED_TERRACOTTA"}),
    BLACK_SHULKER_BOX("BLACK_SHULKER_BOX", 0, new String[]{"BLACK_SHULKER_BOX"}),
    BLACK_STAINED_GLASS("BLACK_STAINED_GLASS", 15, new String[]{"STAINED_GLASS"}),
    BLACK_STAINED_GLASS_PANE("BLACK_STAINED_GLASS_PANE", 15, new String[]{"STAINED_GLASS_PANE"}),
    BLACK_TERRACOTTA("BLACK_TERRACOTTA", 15, new String[]{"STAINED_CLAY"}),
    BLACK_WALL_BANNER("BLACK_WALL_BANNER", 0, new String[]{"WALL_BANNER"}),
    BLACK_WOOL("BLACK_WOOL", 15, new String[]{"WOOL"}),
    BLAZE_POWDER("BLAZE_POWDER", 0, new String[]{"BLAZE_POWDER"}),
    BLAZE_ROD("BLAZE_ROD", 0, new String[]{"BLAZE_ROD"}),
    BLAZE_SPAWN_EGG("BLAZE_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    BLUE_BANNER("BLUE_BANNER", 11, new String[]{"BANNER", "STANDING_BANNER"}),
    BLUE_BED("BLUE_BED", 4, new String[]{"BED", "BED_BLOCK"}),
    BLUE_CARPET("BLUE_CARPET", 11, new String[]{"CARPET"}),
    BLUE_CONCRETE("BLUE_CONCRETE", 11, new String[]{"CONCRETE"}),
    BLUE_CONCRETE_POWDER("BLUE_CONCRETE_POWDER", 11, new String[]{"CONCRETE_POWDER"}),
    BLUE_DYE("BLUE_DYE", 4, new String[]{"INK_SACK"}),
    BLUE_GLAZED_TERRACOTTA("BLUE_GLAZED_TERRACOTTA", 0, new String[]{"BLUE_GLAZED_TERRACOTTA"}),
    BLUE_ICE("BLUE_ICE", 0, new String[]{"PACKED_ICE"}),
    BLUE_ORCHID("BLUE_ORCHID", 1, new String[]{"RED_ROSE"}),
    BLUE_SHULKER_BOX("BLUE_SHULKER_BOX", 0, new String[]{"BLUE_SHULKER_BOX"}),
    BLUE_STAINED_GLASS("BLUE_STAINED_GLASS", 11, new String[]{"STAINED_GLASS"}),
    BLUE_STAINED_GLASS_PANE("BLUE_STAINED_GLASS_PANE", 11, new String[]{"STAINED_GLASS_PANE"}),
    BLUE_TERRACOTTA("BLUE_TERRACOTTA", 11, new String[]{"STAINED_CLAY"}),
    BLUE_WALL_BANNER("BLUE_WALL_BANNER", 11, new String[]{"WALL_BANNER"}),
    BLUE_WOOL("BLUE_WOOL", 11, new String[]{"WOOL"}),
    BONE("BONE", 0, new String[]{"BONE"}),
    BONE_BLOCK("BONE_BLOCK", 0, new String[]{"BONE_BLOCK"}),
    BONE_MEAL("BONE_MEAL", 15, new String[]{"INK_SACK"}),
    BOOK("BOOK", 0, new String[]{"BOOK"}),
    BOOKSHELF("BOOKSHELF", 0, new String[]{"BOOKSHELF"}),
    BOW("BOW", 0, new String[]{"BOW"}),
    BOWL("BOWL", 0, new String[]{"BOWL"}),
    BRAIN_CORAL("BRAIN_CORAL", 0, new String[]{"STONE"}),
    BRAIN_CORAL_BLOCK("BRAIN_CORAL_BLOCK", 0, new String[]{"STONE"}),
    BRAIN_CORAL_FAN("BRAIN_CORAL_FAN", 0, new String[]{"STONE"}),
    BREAD("BREAD", 0, new String[]{"BREAD"}),
    BREWING_STAND("BREWING_STAND", 0, new String[]{"BREWING_STAND", "BREWING_STAND_ITEM"}),
    BRICK("BRICK", 0, new String[]{"CLAY_BRICK"}),
    BRICK_SLAB("BRICK_SLAB", 4, new String[]{"STEP"}),
    BRICK_STAIRS("BRICK_STAIRS", 0, new String[]{"BRICK_STAIRS"}),
    BRICKS("BRICKS", 0, new String[]{"BRICK"}),
    BROWN_BANNER("BROWN_BANNER", 3, new String[]{"BANNER", "STANDING_BANNER"}),
    BROWN_BED("BROWN_BED", 12, new String[]{"BED", "BED_BLOCK"}),
    BROWN_CARPET("BROWN_CARPET", 12, new String[]{"CARPET"}),
    BROWN_CONCRETE("BROWN_CONCRETE", 12, new String[]{"CONCRETE"}),
    BROWN_CONCRETE_POWDER("BROWN_CONCRETE_POWDER", 12, new String[]{"CONCRETE_POWDER"}),
    BROWN_DYE("BROWN_DYE", 3, new String[]{"INK_SACK"}),
    BROWN_GLAZED_TERRACOTTA("BROWN_GLAZED_TERRACOTTA", 0, new String[]{"BROWN_GLAZED_TERRACOTTA"}),
    BROWN_MUSHROOM("BROWN_MUSHROOM", 0, new String[]{"BROWN_MUSHROOM"}),
    BROWN_MUSHROOM_BLOCK("BROWN_MUSHROOM_BLOCK", 0, new String[]{"BROWN_MUSHROOM", "HUGE_MUSHROOM_1"}),
    BROWN_SHULKER_BOX("BROWN_SHULKER_BOX", 0, new String[]{"BROWN_SHULKER_BOX"}),
    BROWN_STAINED_GLASS("BROWN_STAINED_GLASS", 12, new String[]{"STAINED_GLASS"}),
    BROWN_STAINED_GLASS_PANE("BROWN_STAINED_GLASS_PANE", 12, new String[]{"STAINED_GLASS_PANE"}),
    BROWN_TERRACOTTA("BROWN_TERRACOTTA", 12, new String[]{"STAINED_CLAY"}),
    BROWN_WALL_BANNER("BROWN_WALL_BANNER", 3, new String[]{"WALL_BANNER"}),
    BROWN_WOOL("BROWN_WOOL", 12, new String[]{"WOOL"}),
    BUBBLE_COLUMN("BUBBLE_COLUMN", 0, new String[]{"STONE"}),
    BUBBLE_CORAL("BUBBLE_CORAL", 0, new String[]{"STONE"}),
    BUBBLE_CORAL_BLOCK("BUBBLE_CORAL_BLOCK", 0, new String[]{"STONE"}),
    BUBBLE_CORAL_FAN("BUBBLE_CORAL_FAN", 0, new String[]{"STONE"}),
    BUCKET("BUCKET", 0, new String[]{"BUCKET"}),
    CACTUS("CACTUS", 0, new String[]{"CACTUS"}),
    CACTUS_GREEN("CACTUS_GREEN", 2, new String[]{"INK_SACK", "GREEN_DYE"}),
    CAKE("CAKE", 0, new String[]{"CAKE", "CAKE_BLOCK"}),
    CARROT("CARROT", 0, new String[]{"CARROT_ITEM"}),
    CARROT_ON_A_STICK("CARROT_ON_A_STICK", 0, new String[]{"CARROT_STICK"}),
    CARROTS("CARROTS", 0, new String[]{"CARROT"}),
    CARVED_PUMPKIN("CARVED_PUMPKIN", 0, new String[]{"PUMPKIN"}),
    CAULDRON("CAULDRON", 0, new String[]{"CAULDRON", "CAULDRON_ITEM"}),
    CAVE_AIR("CAVE_AIR", 0, new String[]{"AIR"}),
    CAVE_SPIDER_SPAWN_EGG("CAVE_SPIDER_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    CHAIN_COMMAND_BLOCK("CHAIN_COMMAND_BLOCK", 0, new String[]{"COMMAND_CHAIN"}),
    CHAINMAIL_BOOTS("CHAINMAIL_BOOTS", 0, new String[]{"CHAINMAIL_BOOTS"}),
    CHAINMAIL_CHESTPLATE("CHAINMAIL_CHESTPLATE", 0, new String[]{"CHAINMAIL_CHESTPLATE"}),
    CHAINMAIL_HELMET("CHAINMAIL_HELMET", 0, new String[]{"CHAINMAIL_HELMET"}),
    CHAINMAIL_LEGGINGS("CHAINMAIL_LEGGINGS", 0, new String[]{"CHAINMAIL_LEGGINGS"}),
    CHARCOAL("CHARCOAL", 1, new String[]{"COAL"}),
    CHEST("CHEST", 0, new String[]{"CHEST", "LOCKED_CHEST"}),
    CHEST_D("CHEST", 6, new String[]{"CHEST", "LOCKED_CHEST"}),
    CHEST_MINECART("CHEST_MINECART", 0, new String[]{"STORAGE_MINECART"}),
    CHEST_N("CHEST", 1, new String[]{"CHEST", "LOCKED_CHEST"}),
    CHEST_O("CHEST", 4, new String[]{"CHEST", "LOCKED_CHEST"}),
    CHEST_S("CHEST", 2, new String[]{"CHEST", "LOCKED_CHEST"}),
    CHEST_U("CHEST", 5, new String[]{"CHEST", "LOCKED_CHEST"}),
    CHEST_W("CHEST", 3, new String[]{"CHEST", "LOCKED_CHEST"}),
    CHICKEN("CHICKEN", 0, new String[]{"RAW_CHICKEN"}),
    CHICKEN_SPAWN_EGG("CHICKEN_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    CHIPPED_ANVIL("CHIPPED_ANVIL", 1, new String[]{"ANVIL"}),
    CHISELED_QUARTZ_BLOCK("CHISELED_QUARTZ_BLOCK", 1, new String[]{"QUARTZ_BLOCK"}),
    CHISELED_RED_SANDSTONE("CHISELED_RED_SANDSTONE", 1, new String[]{"RED_SANDSTONE"}),
    CHISELED_SANDSTONE("CHISELED_SANDSTONE", 1, new String[]{"SANDSTONE"}),
    CHISELED_STONE_BRICKS("CHISELED_STONE_BRICKS", 3, new String[]{"SMOOTH_BRICK"}),
    CHORUS_FLOWER("CHORUS_FLOWER", 0, new String[]{"CHORUS_FLOWER"}),
    CHORUS_FRUIT("CHORUS_FRUIT", 0, new String[]{"CHORUS_FRUIT"}),
    CHORUS_PLANT("CHORUS_PLANT", 0, new String[]{"CHORUS_PLANT"}),
    CLAY("CLAY", 0, new String[]{"CLAY"}),
    CLAY_BALL("CLAY_BALL", 0, new String[]{"CLAY_BALL"}),
    CLOCK("CLOCK", 0, new String[]{"WATCH"}),
    COAL("COAL", 0, new String[]{"COAL"}),
    COAL_BLOCK("COAL_BLOCK", 0, new String[]{"COAL_BLOCK"}),
    COAL_ORE("COAL_ORE", 0, new String[]{"COAL_ORE"}),
    COARSE_DIRT("COARSE_DIRT", 1, new String[]{"DIRT"}),
    COBBLESTONE("COBBLESTONE", 0, new String[]{"COBBLESTONE"}),
    COBBLESTONE_SLAB("COBBLESTONE_SLAB", 3, new String[]{"STEP"}),
    COBBLESTONE_STAIRS("COBBLESTONE_STAIRS", 0, new String[]{"COBBLESTONE_STAIRS"}),
    COBBLESTONE_WALL("COBBLESTONE_WALL", 0, new String[]{"COBBLE_WALL"}),
    COBWEB("COBWEB", 0, new String[]{"WEB"}),
    COCOA("COCOA", 0, new String[]{"COCOA"}),
    COCOA_BEANS("COCOA_BEANS", 3, new String[]{"INK_SACK"}),
    COD("COD", 0, new String[]{"RAW_FISH"}),
    COD_BUCKET("COD_BUCKET", 0, new String[]{"BUCKET"}),
    COD_SPAWN_EGG("COD_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    COMMAND_BLOCK("COMMAND_BLOCK", 0, new String[]{"COMMAND"}),
    COMMAND_BLOCK_MINECART("COMMAND_BLOCK_MINECART", 0, new String[]{"COMMAND_MINECART"}),
    COMPARATOR("COMPARATOR", 0, new String[]{"REDSTONE_COMPARATOR", "REDSTONE_COMPARATOR_ON", "REDSTONE_COMPARATOR_OFF"}),
    COMPASS("COMPASS", 0, new String[]{"COMPASS"}),
    CONDUIT("CONDUIT", 0, new String[]{"STONE"}),
    COOKED_BEEF("COOKED_BEEF", 0, new String[]{"COOKED_BEEF"}),
    COOKED_CHICKEN("COOKED_CHICKEN", 0, new String[]{"COOKED_CHICKEN"}),
    COOKED_COD("COOKED_COD", 0, new String[]{"COOKED_FISH"}),
    COOKED_MUTTON("COOKED_MUTTON", 0, new String[]{"COOKED_MUTTON"}),
    COOKED_PORKCHOP("COOKED_PORKCHOP", 0, new String[]{"GRILLED_PORK"}),
    COOKED_RABBIT("COOKED_RABBIT", 0, new String[]{"COOKED_RABBIT"}),
    COOKED_SALMON("COOKED_SALMON", 1, new String[]{"COOKED_FISH"}),
    COOKIE("COOKIE", 0, new String[]{"COOKIE"}),
    COW_SPAWN_EGG("COW_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    CRACKED_STONE_BRICKS("CRACKED_STONE_BRICKS", 2, new String[]{"SMOOTH_BRICK"}),
    CRAFTING_TABLE("CRAFTING_TABLE", 0, new String[]{"WORKBENCH"}),
    CREEPER_HEAD("CREEPER_HEAD", 0, new String[]{"SKULL", "SKULL_ITEM"}),
    CREEPER_SPAWN_EGG("CREEPER_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    CREEPER_WALL_HEAD("CREEPER_WALL_HEAD", 0, new String[]{"SKULL", "SKULL_ITEM"}),
    CUT_RED_SANDSTONE("CUT_RED_SANDSTONE", 0, new String[]{"STONE"}),
    CUT_SANDSTONE("CUT_SANDSTONE", 0, new String[]{"STONE"}),
    CYAN_BANNER("CYAN_BANNER", 6, new String[]{"BANNER", "STANDING_BANNER"}),
    CYAN_BED("CYAN_BED", 9, new String[]{"BED", "BED_BLOCK"}),
    CYAN_CARPET("CYAN_CARPET", 9, new String[]{"CARPET"}),
    CYAN_CONCRETE("CYAN_CONCRETE", 9, new String[]{"CONCRETE"}),
    CYAN_CONCRETE_POWDER("CYAN_CONCRETE_POWDER", 9, new String[]{"CONCRETE_POWDER"}),
    CYAN_DYE("CYAN_DYE", 6, new String[]{"INK_SACK"}),
    CYAN_GLAZED_TERRACOTTA("CYAN_GLAZED_TERRACOTTA", 0, new String[]{"CYAN_GLAZED_TERRACOTTA"}),
    CYAN_SHULKER_BOX("CYAN_SHULKER_BOX", 0, new String[]{"CYAN_SHULKER_BOX"}),
    CYAN_STAINED_GLASS("CYAN_STAINED_GLASS", 9, new String[]{"STAINED_GLASS"}),
    CYAN_STAINED_GLASS_PANE("CYAN_STAINED_GLASS_PANE", 9, new String[]{"STAINED_GLASS_PANE"}),
    CYAN_TERRACOTTA("CYAN_TERRACOTTA", 9, new String[]{"STAINED_CLAY"}),
    CYAN_WALL_BANNER("CYAN_WALL_BANNER", 0, new String[]{"WALL_BANNER"}),
    CYAN_WOOL("CYAN_WOOL", 9, new String[]{"WOOL"}),
    DAMAGED_ANVIL("DAMAGED_ANVIL", 2, new String[]{"ANVIL"}),
    DANDELION("DANDELION", 0, new String[]{"YELLOW_FLOWER"}),
    DANDELION_YELLOW("DANDELION_YELLOW", 11, new String[]{"INK_SACK", "YELLOW_DYE"}),
    DARK_OAK_BOAT("DARK_OAK_BOAT", 0, new String[]{"BOAT_DARK_OAK"}),
    DARK_OAK_BUTTON("DARK_OAK_BUTTON", 0, new String[]{"WOOD_BUTTON"}),
    DARK_OAK_DOOR("DARK_OAK_DOOR", 0, new String[]{"DARK_OAK_DOOR", "DARK_OAK_DOOR_ITEM"}),
    DARK_OAK_FENCE("DARK_OAK_FENCE", 0, new String[]{"DARK_OAK_FENCE"}),
    DARK_OAK_FENCE_GATE("DARK_OAK_FENCE_GATE", 0, new String[]{"DARK_OAK_FENCE_GATE"}),
    DARK_OAK_LEAVES("DARK_OAK_LEAVES", 1, new String[]{"LEAVES_2"}),
    DARK_OAK_LOG("DARK_OAK_LOG", 1, new String[]{"LOG_2"}),
    DARK_OAK_PLANKS("DARK_OAK_PLANKS", 5, new String[]{"WOOD"}),
    DARK_OAK_PRESSURE_PLATE("DARK_OAK_PRESSURE_PLATE", 0, new String[]{"WOOD_PLATE"}),
    DARK_OAK_SAPLING("DARK_OAK_SAPLING", 5, new String[]{"SAPLING"}),
    DARK_OAK_SLAB("DARK_OAK_SLAB", 0, new String[]{"WOODEN_SLAB", "WOOD_STEP", "WOOD_DOUBLE_STEP"}),
    DARK_OAK_STAIRS("DARK_OAK_STAIRS", 0, new String[]{"DARK_OAK_STAIRS"}),
    DARK_OAK_TRAPDOOR("DARK_OAK_TRAPDOOR", 0, new String[]{"TRAP_DOOR"}),
    DARK_OAK_WOOD("DARK_OAK_WOOD", 1, new String[]{"LOG_2"}),
    DARK_PRISMARINE("DARK_PRISMARINE", 2, new String[]{"PRISMARINE"}),
    DARK_PRISMARINE_SLAB("DARK_PRISMARINE_SLAB", 0, new String[]{"STONE"}),
    DARK_PRISMARINE_STAIRS("DARK_PRISMARINE_STAIRS", 0, new String[]{"STONE"}),
    DAYLIGHT_DETECTOR("DAYLIGHT_DETECTOR", 0, new String[]{"DAYLIGHT_DETECTOR", "DAYLIGHT_DETECTOR_INVERTED"}),
    DEAD_BRAIN_CORAL_BLOCK("DEAD_BRAIN_CORAL_BLOCK", 0, new String[]{"STONE"}),
    DEAD_BUBBLE_CORAL_BLOCK("DEAD_BUBBLE_CORAL_BLOCK", 0, new String[]{"STONE"}),
    DEAD_BUSH("DEAD_BUSH", 0, new String[]{"DEAD_BUSH"}),
    DEAD_FIRE_CORAL_BLOCK("DEAD_FIRE_CORAL_BLOCK", 0, new String[]{"STONE"}),
    DEAD_HORN_CORAL_BLOCK("DEAD_HORN_CORAL_BLOCK", 0, new String[]{"STONE"}),
    DEAD_TUBE_CORAL_BLOCK("DEAD_TUBE_CORAL_BLOCK", 0, new String[]{"STONE"}),
    DEBUG_STICK("DEBUG_STICK", 0, new String[]{"STICK"}),
    DETECTOR_RAIL("DETECTOR_RAIL", 0, new String[]{"DETECTOR_RAIL"}),
    DIAMOND("DIAMOND", 0, new String[]{"DIAMOND"}),
    DIAMOND_AXE("DIAMOND_AXE", 0, new String[]{"DIAMOND_AXE"}),
    DIAMOND_BLOCK("DIAMOND_BLOCK", 0, new String[]{"DIAMOND_BLOCK"}),
    DIAMOND_BOOTS("DIAMOND_BOOTS", 0, new String[]{"DIAMOND_BOOTS"}),
    DIAMOND_CHESTPLATE("DIAMOND_CHESTPLATE", 0, new String[]{"DIAMOND_CHESTPLATE"}),
    DIAMOND_HELMET("DIAMOND_HELMET", 0, new String[]{"DIAMOND_HELMET"}),
    DIAMOND_HOE("DIAMOND_HOE", 0, new String[]{"DIAMOND_HOE"}),
    DIAMOND_HORSE_ARMOR("DIAMOND_HORSE_ARMOR", 0, new String[]{"DIAMOND_BARDING"}),
    DIAMOND_LEGGINGS("DIAMOND_LEGGINGS", 0, new String[]{"DIAMOND_LEGGINGS"}),
    DIAMOND_ORE("DIAMOND_ORE", 0, new String[]{"DIAMOND_ORE"}),
    DIAMOND_PICKAXE("DIAMOND_PICKAXE", 0, new String[]{"DIAMOND_PICKAXE"}),
    DIAMOND_SHOVEL("DIAMOND_SHOVEL", 0, new String[]{"DIAMOND_SPADE"}),
    DIAMOND_SWORD("DIAMOND_SWORD", 0, new String[]{"DIAMOND_SWORD"}),
    DIORITE("DIORITE", 3, new String[]{"STONE"}),
    DIRT("DIRT", 0, new String[]{"DIRT"}),
    DISPENSER("DISPENSER", 0, new String[]{"DISPENSER"}),
    DOLPHIN_SPAWN_EGG("DOLPHIN_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    DONKEY_SPAWN_EGG("DONKEY_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    DRAGON_BREATH("DRAGON_BREATH", 0, new String[]{"DRAGONS_BREATH"}),
    DRAGON_EGG("DRAGON_EGG", 0, new String[]{"DRAGON_EGG"}),
    DRAGON_HEAD("DRAGON_HEAD", 5, new String[]{"SKULL", "SKULL_ITEM"}),
    DRAGON_WALL_HEAD("DRAGON_WALL_HEAD", 0, new String[]{"SKULL", "SKULL_ITEM"}),
    DRIED_KELP("DRIED_KELP", 0, new String[]{"STONE"}),
    DRIED_KELP_BLOCK("DRIED_KELP_BLOCK", 0, new String[]{"STONE"}),
    DROPPER("DROPPER", 0, new String[]{"DROPPER"}),
    DROWNED_SPAWN_EGG("DROWNED_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    EGG("EGG", 0, new String[]{"EGG"}),
    ELDER_GUARDIAN_SPAWN_EGG("ELDER_GUARDIAN_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    ELYTRA("ELYTRA", 0, new String[]{"ELYTRA"}),
    EMERALD("EMERALD", 0, new String[]{"EMERALD"}),
    EMERALD_BLOCK("EMERALD_BLOCK", 0, new String[]{"EMERALD_BLOCK"}),
    EMERALD_ORE("EMERALD_ORE", 0, new String[]{"EMERALD_ORE"}),
    ENCHANTED_BOOK("ENCHANTED_BOOK", 0, new String[]{"ENCHANTED_BOOK"}),
    ENCHANTED_GOLDEN_APPLE("ENCHANTED_GOLDEN_APPLE", 1, new String[]{"GOLDEN_APPLE"}),
    ENCHANTING_TABLE("ENCHANTING_TABLE", 0, new String[]{"ENCHANTMENT_TABLE"}),
    END_CRYSTAL("END_CRYSTAL", 0, new String[]{"END_CRYSTAL"}),
    END_GATEWAY("END_GATEWAY", 0, new String[]{"END_GATEWAY"}),
    END_PORTAL("END_PORTAL", 0, new String[]{"ENDER_PORTAL"}),
    END_PORTAL_FRAME("END_PORTAL_FRAME", 0, new String[]{"ENDER_PORTAL_FRAME"}),
    END_ROD("END_ROD", 0, new String[]{"END_ROD"}),
    END_STONE("END_STONE", 0, new String[]{"ENDER_STONE"}),
    END_STONE_BRICKS("END_STONE_BRICKS", 0, new String[]{"END_BRICKS"}),
    ENDER_CHEST("ENDER_CHEST", 0, new String[]{"ENDER_CHEST"}),
    ENDER_EYE("ENDER_EYE", 0, new String[]{"EYE_OF_ENDER"}),
    ENDER_PEARL("ENDER_PEARL", 0, new String[]{"ENDER_PEARL"}),
    ENDERMAN_SPAWN_EGG("ENDERMAN_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    ENDERMITE_SPAWN_EGG("ENDERMITE_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    EVOKER_SPAWN_EGG("EVOKER_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    EXPERIENCE_BOTTLE("EXPERIENCE_BOTTLE", 0, new String[]{"EXP_BOTTLE"}),
    FARMLAND("FARMLAND", 0, new String[]{"SOIL"}),
    FEATHER("FEATHER", 0, new String[]{"FEATHER"}),
    FERMENTED_SPIDER_EYE("FERMENTED_SPIDER_EYE", 0, new String[]{"FERMENTED_SPIDER_EYE"}),
    FERN("FERN", 2, new String[]{"LONG_GRASS"}),
    FERN_1("FERN", 1, new String[]{"LONG_GRASS"}),
    FILLED_MAP("FILLED_MAP", 0, new String[]{"MAP"}),
    FIRE("FIRE", 0, new String[]{"FIRE"}),
    FIRE_CHARGE("FIRE_CHARGE", 0, new String[]{"FIREBALL"}),
    FIRE_CORAL("FIRE_CORAL", 0, new String[]{"STONE"}),
    FIRE_CORAL_BLOCK("FIRE_CORAL_BLOCK", 0, new String[]{"STONE"}),
    FIRE_CORAL_FAN("FIRE_CORAL_FAN", 0, new String[]{"STONE"}),
    FIREWORK_ROCKET("FIREWORK_ROCKET", 0, new String[]{"FIREWORK"}),
    FIREWORK_STAR("FIREWORK_STAR", 0, new String[]{"FIREWORK_CHARGE"}),
    FISHING_ROD("FISHING_ROD", 0, new String[]{"FISHING_ROD"}),
    FLINT("FLINT", 0, new String[]{"FLINT"}),
    FLINT_AND_STEEL("FLINT_AND_STEEL", 0, new String[]{"FLINT_AND_STEEL"}),
    FLOWER_POT("FLOWER_POT", 0, new String[]{"FLOWER_POT", "FLOWER_POT_ITEM"}),
    FROSTED_ICE("FROSTED_ICE", 0, new String[]{"FROSTED_ICE"}),
    FURNACE("FURNACE", 0, new String[]{"FURNACE", "BURNING_FURNACE"}),
    FURNACE_MINECART("FURNACE_MINECART", 0, new String[]{"POWERED_MINECART"}),
    GHAST_SPAWN_EGG("GHAST_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    GHAST_TEAR("GHAST_TEAR", 0, new String[]{"GHAST_TEAR"}),
    GLASS("GLASS", 0, new String[]{"GLASS"}),
    GLASS_BOTTLE("GLASS_BOTTLE", 0, new String[]{"GLASS_BOTTLE"}),
    GLASS_PANE("GLASS_PANE", 0, new String[]{"THIN_GLASS"}),
    GLISTERING_MELON_SLICE("GLISTERING_MELON_SLICE", 0, new String[]{"SPECKLED_MELON"}),
    GLOWSTONE("GLOWSTONE", 0, new String[]{"GLOWSTONE"}),
    GLOWSTONE_DUST("GLOWSTONE_DUST", 0, new String[]{"GLOWSTONE_DUST"}),
    GOLD_BLOCK("GOLD_BLOCK", 0, new String[]{"GOLD_BLOCK"}),
    GOLD_INGOT("GOLD_INGOT", 0, new String[]{"GOLD_INGOT"}),
    GOLD_NUGGET("GOLD_NUGGET", 0, new String[]{"GOLD_NUGGET"}),
    GOLD_ORE("GOLD_ORE", 0, new String[]{"GOLD_ORE"}),
    GOLDEN_APPLE("GOLDEN_APPLE", 0, new String[]{"GOLDEN_APPLE"}),
    GOLDEN_AXE("GOLDEN_AXE", 0, new String[]{"GOLD_AXE"}),
    GOLDEN_BOOTS("GOLDEN_BOOTS", 0, new String[]{"GOLD_BOOTS"}),
    GOLDEN_CARROT("GOLDEN_CARROT", 0, new String[]{"GOLDEN_CARROT"}),
    GOLDEN_CHESTPLATE("GOLDEN_CHESTPLATE", 0, new String[]{"GOLD_CHESTPLATE"}),
    GOLDEN_HELMET("GOLDEN_HELMET", 0, new String[]{"GOLD_HELMET"}),
    GOLDEN_HOE("GOLDEN_HOE", 0, new String[]{"GOLD_HOE"}),
    GOLDEN_HORSE_ARMOR("GOLDEN_HORSE_ARMOR", 0, new String[]{"GOLD_BARDING"}),
    GOLDEN_LEGGINGS("GOLDEN_LEGGINGS", 0, new String[]{"GOLD_LEGGINGS"}),
    GOLDEN_PICKAXE("GOLDEN_PICKAXE", 0, new String[]{"GOLD_PICKAXE"}),
    GOLDEN_SHOVEL("GOLDEN_SHOVEL", 0, new String[]{"GOLD_SPADE"}),
    GOLDEN_SWORD("GOLDEN_SWORD", 0, new String[]{"GOLD_SWORD"}),
    GRANITE("GRANITE", 1, new String[]{"STONE"}),
    GRASS("GRASS", 0, new String[]{"GRASS"}),
    GRASS_BLOCK("GRASS_BLOCK", 0, new String[]{"GRASS"}),
    GRASS_PATH("GRASS_PATH", 0, new String[]{"GRASS_PATH"}),
    GRAVEL("GRAVEL", 0, new String[]{"GRAVEL"}),
    GRAY_BANNER("GRAY_BANNER", 8, new String[]{"BANNER", "STANDING_BANNER"}),
    GRAY_BED("GRAY_BED", 7, new String[]{"BED", "BED_BLOCK"}),
    GRAY_CARPET("GRAY_CARPET", 7, new String[]{"CARPET"}),
    GRAY_CONCRETE("GRAY_CONCRETE", 7, new String[]{"CONCRETE"}),
    GRAY_CONCRETE_POWDER("GRAY_CONCRETE_POWDER", 7, new String[]{"CONCRETE_POWDER"}),
    GRAY_DYE("GRAY_DYE", 8, new String[]{"INK_SACK"}),
    GRAY_GLAZED_TERRACOTTA("GRAY_GLAZED_TERRACOTTA", 0, new String[]{"GRAY_GLAZED_TERRACOTTA"}),
    GRAY_SHULKER_BOX("GRAY_SHULKER_BOX", 0, new String[]{"GRAY_SHULKER_BOX"}),
    GRAY_STAINED_GLASS("GRAY_STAINED_GLASS", 7, new String[]{"STAINED_GLASS"}),
    GRAY_STAINED_GLASS_PANE("GRAY_STAINED_GLASS_PANE", 7, new String[]{"STAINED_GLASS_PANE"}),
    GRAY_TERRACOTTA("GRAY_TERRACOTTA", 7, new String[]{"STAINED_CLAY"}),
    GRAY_WALL_BANNER("GRAY_WALL_BANNER", 0, new String[]{"WALL_BANNER"}),
    GRAY_WOOL("GRAY_WOOL", 7, new String[]{"WOOL"}),
    GREEN_BANNER("GREEN_BANNER", 2, new String[]{"BANNER", "STANDING_BANNER"}),
    GREEN_BED("GREEN_BED", 13, new String[]{"BED", "BED_BLOCK"}),
    GREEN_CARPET("GREEN_CARPET", 13, new String[]{"CARPET"}),
    GREEN_CONCRETE("GREEN_CONCRETE", 13, new String[]{"CONCRETE"}),
    GREEN_CONCRETE_POWDER("GREEN_CONCRETE_POWDER", 13, new String[]{"CONCRETE_POWDER"}),
    GREEN_DYE("GREEN_DYE", 2, new String[]{"INK_SACK", "CACTUS_GREEN"}),
    GREEN_GLAZED_TERRACOTTA("GREEN_GLAZED_TERRACOTTA", 0, new String[]{"GREEN_GLAZED_TERRACOTTA"}),
    GREEN_SHULKER_BOX("GREEN_SHULKER_BOX", 0, new String[]{"GREEN_SHULKER_BOX"}),
    GREEN_STAINED_GLASS("GREEN_STAINED_GLASS", 13, new String[]{"STAINED_GLASS"}),
    GREEN_STAINED_GLASS_PANE("GREEN_STAINED_GLASS_PANE", 13, new String[]{"STAINED_GLASS_PANE"}),
    GREEN_TERRACOTTA("GREEN_TERRACOTTA", 13, new String[]{"STAINED_CLAY"}),
    GREEN_WALL_BANNER("GREEN_WALL_BANNER", 0, new String[]{"WALL_BANNER"}),
    GREEN_WOOL("GREEN_WOOL", 13, new String[]{"WOOL"}),
    GUARDIAN_SPAWN_EGG("GUARDIAN_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    GUNPOWDER("GUNPOWDER", 0, new String[]{"SULPHUR"}),
    HAY_BLOCK("HAY_BLOCK", 0, new String[]{"HAY_BLOCK"}),
    HEART_OF_THE_SEA("HEART_OF_THE_SEA", 0, new String[]{"STONE"}),
    HEAVY_WEIGHTED_PRESSURE_PLATE("HEAVY_WEIGHTED_PRESSURE_PLATE", 0, new String[]{"IRON_PLATE"}),
    HOPPER("HOPPER", 0, new String[]{"HOPPER"}),
    HOPPER_MINECART("HOPPER_MINECART", 0, new String[]{"HOPPER_MINECART"}),
    HORN_CORAL("HORN_CORAL", 0, new String[]{"STONE"}),
    HORN_CORAL_BLOCK("HORN_CORAL_BLOCK", 0, new String[]{"STONE"}),
    HORN_CORAL_FAN("HORN_CORAL_FAN", 0, new String[]{"STONE"}),
    HORSE_SPAWN_EGG("HORSE_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    HUSK_SPAWN_EGG("HUSK_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    ICE("ICE", 0, new String[]{"ICE"}),
    INFESTED_CHISELED_STONE_BRICKS("INFESTED_CHISELED_STONE_BRICKS", 5, new String[]{"MONSTER_EGGS"}),
    INFESTED_COBBLESTONE("INFESTED_COBBLESTONE", 1, new String[]{"MONSTER_EGGS"}),
    INFESTED_CRACKED_STONE_BRICKS("INFESTED_CRACKED_STONE_BRICKS", 4, new String[]{"MONSTER_EGGS"}),
    INFESTED_MOSSY_STONE_BRICKS("INFESTED_MOSSY_STONE_BRICKS", 3, new String[]{"MONSTER_EGGS"}),
    INFESTED_STONE("INFESTED_STONE", 0, new String[]{"MONSTER_EGGS"}),
    INFESTED_STONE_BRICKS("INFESTED_STONE_BRICKS", 2, new String[]{"MONSTER_EGGS"}),
    INK_SAC("INK_SAC", 0, new String[]{"INK_SACK"}),
    IRON_AXE("IRON_AXE", 0, new String[]{"IRON_AXE"}),
    IRON_BARS("IRON_BARS", 0, new String[]{"IRON_FENCE"}),
    IRON_BLOCK("IRON_BLOCK", 0, new String[]{"IRON_BLOCK"}),
    IRON_BOOTS("IRON_BOOTS", 0, new String[]{"IRON_BOOTS"}),
    IRON_CHESTPLATE("IRON_CHESTPLATE", 0, new String[]{"IRON_CHESTPLATE"}),
    IRON_DOOR("IRON_DOOR", 0, new String[]{"IRON_DOOR", "IRON_DOOR_BLOCK"}),
    IRON_HELMET("IRON_HELMET", 0, new String[]{"IRON_HELMET"}),
    IRON_HOE("IRON_HOE", 0, new String[]{"IRON_HOE"}),
    IRON_HORSE_ARMOR("IRON_HORSE_ARMOR", 0, new String[]{"IRON_BARDING"}),
    IRON_INGOT("IRON_INGOT", 0, new String[]{"IRON_INGOT"}),
    IRON_LEGGINGS("IRON_LEGGINGS", 0, new String[]{"IRON_LEGGINGS"}),
    IRON_NUGGET("IRON_NUGGET", 0, new String[]{"IRON_NUGGET"}),
    IRON_ORE("IRON_ORE", 0, new String[]{"IRON_ORE"}),
    IRON_PICKAXE("IRON_PICKAXE", 0, new String[]{"IRON_PICKAXE"}),
    IRON_SHOVEL("IRON_SHOVEL", 0, new String[]{"IRON_SPADE"}),
    IRON_SWORD("IRON_SWORD", 0, new String[]{"IRON_SWORD"}),
    IRON_TRAPDOOR("IRON_TRAPDOOR", 0, new String[]{"IRON_TRAPDOOR"}),
    ITEM_FRAME("ITEM_FRAME", 0, new String[]{"ITEM_FRAME"}),
    JACK_O_LANTERN("JACK_O_LANTERN", 0, new String[]{"JACK_O_LANTERN"}),
    JUKEBOX("JUKEBOX", 0, new String[]{"JUKEBOX"}),
    JUNGLE_BOAT("JUNGLE_BOAT", 0, new String[]{"BOAT_JUNGLE"}),
    JUNGLE_BUTTON("JUNGLE_BUTTON", 0, new String[]{"WOOD_BUTTON"}),
    JUNGLE_DOOR("JUNGLE_DOOR", 0, new String[]{"JUNGLE_DOOR", "JUNGLE_DOOR_ITEM"}),
    JUNGLE_FENCE("JUNGLE_FENCE", 0, new String[]{"JUNGLE_FENCE"}),
    JUNGLE_FENCE_GATE("JUNGLE_FENCE_GATE", 0, new String[]{"JUNGLE_FENCE_GATE"}),
    JUNGLE_LEAVES("JUNGLE_LEAVES", 3, new String[]{"LEAVES"}),
    JUNGLE_LOG("JUNGLE_LOG", 3, new String[]{"LOG"}),
    JUNGLE_PLANKS("JUNGLE_PLANKS", 3, new String[]{"WOOD"}),
    JUNGLE_PRESSURE_PLATE("JUNGLE_PRESSURE_PLATE", 0, new String[]{"WOOD_PLATE"}),
    JUNGLE_SAPLING("JUNGLE_SAPLING", 3, new String[]{"SAPLING"}),
    JUNGLE_SLAB("JUNGLE_SLAB", 3, new String[]{"WOODEN_SLAB", "WOOD_STEP", "WOOD_DOUBLE_STEP"}),
    JUNGLE_STAIRS("JUNGLE_STAIRS", 0, new String[]{"JUNGLE_WOOD_STAIRS"}),
    JUNGLE_TRAPDOOR("JUNGLE_TRAPDOOR", 0, new String[]{"TRAP_DOOR"}),
    JUNGLE_WOOD("JUNGLE_WOOD", 3, new String[]{"LOG"}),
    KELP("KELP", 0, new String[]{"STONE"}),
    KELP_PLANT("KELP_PLANT", 0, new String[]{"STONE"}),
    KNOWLEDGE_BOOK("KNOWLEDGE_BOOK", 0, new String[]{"KNOWLEDGE_BOOK"}),
    LADDER("LADDER", 0, new String[]{"LADDER"}),
    LAPIS_BLOCK("LAPIS_BLOCK", 0, new String[]{"LAPIS_BLOCK"}),
    LAPIS_LAZULI("LAPIS_LAZULI", 4, new String[]{"INK_SACK"}),
    LAPIS_ORE("LAPIS_ORE", 0, new String[]{"LAPIS_ORE"}),
    LARGE_FERN("LARGE_FERN", 3, new String[]{"DOUBLE_PLANT"}),
    LARGE_FERN_1("LARGE_FERN", 8, new String[]{"DOUBLE_PLANT"}),
    LAVA("LAVA", 0, new String[]{"LAVA", "STATIONARY_LAVA"}),
    LAVA_BUCKET("LAVA_BUCKET", 0, new String[]{"LAVA_BUCKET"}),
    LEAD("LEAD", 0, new String[]{"LEASH"}),
    LEATHER("LEATHER", 0, new String[]{"LEATHER"}),
    LEATHER_BOOTS("LEATHER_BOOTS", 0, new String[]{"LEATHER_BOOTS"}),
    LEATHER_CHESTPLATE("LEATHER_CHESTPLATE", 0, new String[]{"LEATHER_CHESTPLATE"}),
    LEATHER_HELMET("LEATHER_HELMET", 0, new String[]{"LEATHER_HELMET"}),
    LEATHER_LEGGINGS("LEATHER_LEGGINGS", 0, new String[]{"LEATHER_LEGGINGS"}),
    LEVER("LEVER", 0, new String[]{"LEVER"}),
    LIGHT_BLUE_BANNER("LIGHT_BLUE_BANNER", 12, new String[]{"BANNER", "STANDING_BANNER"}),
    LIGHT_BLUE_BED("LIGHT_BLUE_BED", 3, new String[]{"BED", "BED_BLOCK"}),
    LIGHT_BLUE_CARPET("LIGHT_BLUE_CARPET", 3, new String[]{"CARPET"}),
    LIGHT_BLUE_CONCRETE("LIGHT_BLUE_CONCRETE", 3, new String[]{"CONCRETE"}),
    LIGHT_BLUE_CONCRETE_POWDER("LIGHT_BLUE_CONCRETE_POWDER", 3, new String[]{"CONCRETE_POWDER"}),
    LIGHT_BLUE_DYE("LIGHT_BLUE_DYE", 12, new String[]{"INK_SACK"}),
    LIGHT_BLUE_GLAZED_TERRACOTTA("LIGHT_BLUE_GLAZED_TERRACOTTA", 0, new String[]{"LIGHT_BLUE_GLAZED_TERRACOTTA"}),
    LIGHT_BLUE_SHULKER_BOX("LIGHT_BLUE_SHULKER_BOX", 0, new String[]{"LIGHT_BLUE_SHULKER_BOX"}),
    LIGHT_BLUE_STAINED_GLASS("LIGHT_BLUE_STAINED_GLASS", 3, new String[]{"STAINED_GLASS"}),
    LIGHT_BLUE_STAINED_GLASS_PANE("LIGHT_BLUE_STAINED_GLASS_PANE", 3, new String[]{"STAINED_GLASS_PANE"}),
    LIGHT_BLUE_TERRACOTTA("LIGHT_BLUE_TERRACOTTA", 3, new String[]{"STAINED_CLAY"}),
    LIGHT_BLUE_WALL_BANNER("LIGHT_BLUE_WALL_BANNER", 0, new String[]{"BANNER", "STANDING_BANNER"}),
    LIGHT_BLUE_WOOL("LIGHT_BLUE_WOOL", 3, new String[]{"WOOL"}),
    LIGHT_GRAY_BANNER("LIGHT_GRAY_BANNER", 7, new String[]{"BANNER", "STANDING_BANNER"}),
    LIGHT_GRAY_BED("LIGHT_GRAY_BED", 8, new String[]{"BED", "BED_BLOCK"}),
    LIGHT_GRAY_CARPET("LIGHT_GRAY_CARPET", 8, new String[]{"CARPET"}),
    LIGHT_GRAY_CONCRETE("LIGHT_GRAY_CONCRETE", 8, new String[]{"CONCRETE"}),
    LIGHT_GRAY_CONCRETE_POWDER("LIGHT_GRAY_CONCRETE_POWDER", 8, new String[]{"CONCRETE_POWDER"}),
    LIGHT_GRAY_DYE("LIGHT_GRAY_DYE", 7, new String[]{"INK_SACK"}),
    LIGHT_GRAY_GLAZED_TERRACOTTA("LIGHT_GRAY_GLAZED_TERRACOTTA", 0, new String[]{"SILVER_GLAZED_TERRACOTTA"}),
    LIGHT_GRAY_SHULKER_BOX("LIGHT_GRAY_SHULKER_BOX", 0, new String[]{"SILVER_SHULKER_BOX"}),
    LIGHT_GRAY_STAINED_GLASS("LIGHT_GRAY_STAINED_GLASS", 8, new String[]{"STAINED_GLASS"}),
    LIGHT_GRAY_STAINED_GLASS_PANE("LIGHT_GRAY_STAINED_GLASS_PANE", 8, new String[]{"STAINED_GLASS_PANE"}),
    LIGHT_GRAY_TERRACOTTA("LIGHT_GRAY_TERRACOTTA", 8, new String[]{"STAINED_CLAY"}),
    LIGHT_GRAY_WALL_BANNER("LIGHT_GRAY_WALL_BANNER", 0, new String[]{"WALL_BANNER"}),
    LIGHT_GRAY_WOOL("LIGHT_GRAY_WOOL", 8, new String[]{"WOOL"}),
    LIGHT_WEIGHTED_PRESSURE_PLATE("LIGHT_WEIGHTED_PRESSURE_PLATE", 0, new String[]{"GOLD_PLATE"}),
    LILAC("LILAC", 1, new String[]{"DOUBLE_PLANT"}),
    LILY_PAD("LILY_PAD", 0, new String[]{"WATER_LILY"}),
    LIME_BANNER("LIME_BANNER", 10, new String[]{"BANNER", "STANDING_BANNER"}),
    LIME_BED("LIME_BED", 5, new String[]{"BED", "BED_BLOCK"}),
    LIME_CARPET("LIME_CARPET", 5, new String[]{"CARPET"}),
    LIME_CONCRETE("LIME_CONCRETE", 5, new String[]{"CONCRETE"}),
    LIME_CONCRETE_POWDER("LIME_CONCRETE_POWDER", 5, new String[]{"CONCRETE_POWDER"}),
    LIME_DYE("LIME_DYE", 10, new String[]{"INK_SACK"}),
    LIME_GLAZED_TERRACOTTA("LIME_GLAZED_TERRACOTTA", 0, new String[]{"LIME_GLAZED_TERRACOTTA"}),
    LIME_SHULKER_BOX("LIME_SHULKER_BOX", 0, new String[]{"LIME_SHULKER_BOX"}),
    LIME_STAINED_GLASS("LIME_STAINED_GLASS", 5, new String[]{"STAINED_GLASS"}),
    LIME_STAINED_GLASS_PANE("LIME_STAINED_GLASS_PANE", 5, new String[]{"STAINED_GLASS_PANE"}),
    LIME_TERRACOTTA("LIME_TERRACOTTA", 5, new String[]{"STAINED_CLAY"}),
    LIME_WALL_BANNER("LIME_WALL_BANNER", 0, new String[]{"WALL_BANNER"}),
    LIME_WOOL("LIME_WOOL", 5, new String[]{"WOOL"}),
    LINGERING_POTION("LINGERING_POTION", 0, new String[]{"LINGERING_POTION"}),
    LLAMA_SPAWN_EGG("LLAMA_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    MAGENTA_BANNER("MAGENTA_BANNER", 13, new String[]{"BANNER", "STANDING_BANNER"}),
    MAGENTA_BED("MAGENTA_BED", 2, new String[]{"BED", "BED_BLOCK"}),
    MAGENTA_CARPET("MAGENTA_CARPET", 2, new String[]{"CARPET"}),
    MAGENTA_CONCRETE("MAGENTA_CONCRETE", 2, new String[]{"CONCRETE"}),
    MAGENTA_CONCRETE_POWDER("MAGENTA_CONCRETE_POWDER", 2, new String[]{"CONCRETE_POWDER"}),
    MAGENTA_DYE("MAGENTA_DYE", 13, new String[]{"INK_SACK"}),
    MAGENTA_GLAZED_TERRACOTTA("MAGENTA_GLAZED_TERRACOTTA", 0, new String[]{"MAGENTA_GLAZED_TERRACOTTA"}),
    MAGENTA_SHULKER_BOX("MAGENTA_SHULKER_BOX", 0, new String[]{"MAGENTA_SHULKER_BOX"}),
    MAGENTA_STAINED_GLASS("MAGENTA_STAINED_GLASS", 2, new String[]{"STAINED_GLASS"}),
    MAGENTA_STAINED_GLASS_PANE("MAGENTA_STAINED_GLASS_PANE", 2, new String[]{"STAINED_GLASS_PANE"}),
    MAGENTA_TERRACOTTA("MAGENTA_TERRACOTTA", 2, new String[]{"STAINED_CLAY"}),
    MAGENTA_WALL_BANNER("MAGENTA_WALL_BANNER", 0, new String[]{"WALL_BANNER"}),
    MAGENTA_WOOL("MAGENTA_WOOL", 2, new String[]{"WOOL"}),
    MAGMA_BLOCK("MAGMA_BLOCK", 0, new String[]{"MAGMA"}),
    MAGMA_CREAM("MAGMA_CREAM", 0, new String[]{"MAGMA_CREAM"}),
    MAGMA_CUBE_SPAWN_EGG("MAGMA_CUBE_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    MAP("MAP", 0, new String[]{"MAP", "EMPTY_MAP"}),
    MELON("MELON", 0, new String[]{"MELON_BLOCK"}),
    MELON_SEEDS("MELON_SEEDS", 0, new String[]{"MELON_SEEDS"}),
    MELON_SLICE("MELON_SLICE", 0, new String[]{"MELON"}),
    MELON_STEM("MELON_STEM", 0, new String[]{"MELON_STEM"}),
    MILK_BUCKET("MILK_BUCKET", 0, new String[]{"MILK_BUCKET"}),
    MINECART("MINECART", 0, new String[]{"MINECART"}),
    MOOSHROOM_SPAWN_EGG("MOOSHROOM_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    MOSSY_COBBLESTONE("MOSSY_COBBLESTONE", 0, new String[]{"MOSSY_COBBLESTONE"}),
    MOSSY_COBBLESTONE_WALL("MOSSY_COBBLESTONE_WALL", 1, new String[]{"COBBLE_WALL"}),
    MOSSY_STONE_BRICKS("MOSSY_STONE_BRICKS", 1, new String[]{"SMOOTH_BRICK"}),
    MOVING_PISTON("MOVING_PISTON", 0, new String[]{"PISTON_MOVING_PIECE"}),
    MULE_SPAWN_EGG("MULE_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    MUSHROOM_STEM("MUSHROOM_STEM", 0, new String[]{"BROWN_MUSHROOM"}),
    MUSHROOM_STEW("MUSHROOM_STEW", 0, new String[]{"MUSHROOM_SOUP"}),
    MUSIC_DISC_11("MUSIC_DISC_11", 0, new String[]{"GOLD_RECORD"}),
    MUSIC_DISC_13("MUSIC_DISC_13", 0, new String[]{"GREEN_RECORD"}),
    MUSIC_DISC_BLOCKS("MUSIC_DISC_BLOCKS", 0, new String[]{"RECORD_3"}),
    MUSIC_DISC_CAT("MUSIC_DISC_CAT", 0, new String[]{"RECORD_4"}),
    MUSIC_DISC_CHIRP("MUSIC_DISC_CHIRP", 0, new String[]{"RECORD_5"}),
    MUSIC_DISC_FAR("MUSIC_DISC_FAR", 0, new String[]{"RECORD_6"}),
    MUSIC_DISC_MALL("MUSIC_DISC_MALL", 0, new String[]{"RECORD_7"}),
    MUSIC_DISC_MELLOHI("MUSIC_DISC_MELLOHI", 0, new String[]{"RECORD_8"}),
    MUSIC_DISC_STAL("MUSIC_DISC_STAL", 0, new String[]{"RECORD_9"}),
    MUSIC_DISC_STRAD("MUSIC_DISC_STRAD", 0, new String[]{"RECORD_10"}),
    MUSIC_DISC_WAIT("MUSIC_DISC_WAIT", 0, new String[]{"RECORD_11"}),
    MUSIC_DISC_WARD("MUSIC_DISC_WARD", 0, new String[]{"RECORD_12"}),
    MUTTON("MUTTON", 0, new String[]{"MUTTON"}),
    MYCELIUM("MYCELIUM", 0, new String[]{"MYCEL"}),
    NAME_TAG("NAME_TAG", 0, new String[]{"NAME_TAG"}),
    NAUTILUS_SHELL("NAUTILUS_SHELL", 0, new String[]{"STONE"}),
    NETHER_BRICK("NETHER_BRICK", 0, new String[]{"NETHER_BRICK"}),
    NETHER_BRICK_FENCE("NETHER_BRICK_FENCE", 0, new String[]{"NETHER_FENCE"}),
    NETHER_BRICK_SLAB("NETHER_BRICK_SLAB", 6, new String[]{"STEP"}),
    NETHER_BRICK_STAIRS("NETHER_BRICK_STAIRS", 0, new String[]{"NETHER_BRICK_STAIRS"}),
    NETHER_BRICKS("NETHER_BRICKS", 0, new String[]{"NETHER_BRICK"}),
    NETHER_PORTAL("NETHER_PORTAL", 0, new String[]{"PORTAL"}),
    NETHER_QUARTZ_ORE("NETHER_QUARTZ_ORE", 0, new String[]{"QUARTZ_ORE"}),
    NETHER_STAR("NETHER_STAR", 0, new String[]{"NETHER_STAR"}),
    NETHER_WART("NETHER_WART", 0, new String[]{"NETHER_STALK"}),
    NETHER_WART_BLOCK("NETHER_WART_BLOCK", 0, new String[]{"NETHER_WART_BLOCK", "NETHER_WARTS"}),
    NETHERRACK("NETHERRACK", 0, new String[]{"NETHERRACK"}),
    NOTE_BLOCK("NOTE_BLOCK", 0, new String[]{"NOTE_BLOCK"}),
    OAK_BOAT("OAK_BOAT", 0, new String[]{"BOAT"}),
    OAK_BUTTON("OAK_BUTTON", 0, new String[]{"WOOD_BUTTON"}),
    OAK_DOOR("OAK_DOOR", 0, new String[]{"WOODEN_DOOR", "WOOD_DOOR"}),
    OAK_FENCE("OAK_FENCE", 0, new String[]{"FENCE"}),
    OAK_FENCE_GATE("OAK_FENCE_GATE", 0, new String[]{"FENCE_GATE"}),
    OAK_LEAVES("OAK_LEAVES", 0, new String[]{"LEAVES"}),
    OAK_LOG("OAK_LOG", 0, new String[]{"LOG"}),
    OAK_PLANKS("OAK_PLANKS", 0, new String[]{"WOOD"}),
    OAK_PRESSURE_PLATE("OAK_PRESSURE_PLATE", 0, new String[]{"WOOD_PLATE"}),
    OAK_SAPLING("OAK_SAPLING", 0, new String[]{"SAPLING"}),
    OAK_SLAB("OAK_SLAB", 0, new String[]{"WOODEN_SLAB", "WOOD_STEP", "WOOD_DOUBLE_STEP"}),
    OAK_STAIRS("OAK_STAIRS", 0, new String[]{"WOOD_STAIRS"}),
    OAK_TRAPDOOR("OAK_TRAPDOOR", 0, new String[]{"TRAP_DOOR"}),
    OAK_WOOD("OAK_WOOD", 0, new String[]{"LOG"}),
    OBSERVER("OBSERVER", 0, new String[]{"OBSERVER"}),
    OBSIDIAN("OBSIDIAN", 0, new String[]{"OBSIDIAN"}),
    OCELOT_SPAWN_EGG("OCELOT_SPAWN_EGG", 0, new String[]{"RECORD_12"}),
    ORANGE_BANNER("ORANGE_BANNER", 14, new String[]{"BANNER", "STANDING_BANNER"}),
    ORANGE_BED("ORANGE_BED", 1, new String[]{"BED", "BED_BLOCK"}),
    ORANGE_CARPET("ORANGE_CARPET", 1, new String[]{"CARPET"}),
    ORANGE_CONCRETE("ORANGE_CONCRETE", 1, new String[]{"CONCRETE"}),
    ORANGE_CONCRETE_POWDER("ORANGE_CONCRETE_POWDER", 1, new String[]{"CONCRETE_POWDER"}),
    ORANGE_DYE("ORANGE_DYE", 14, new String[]{"INK_SACK"}),
    ORANGE_GLAZED_TERRACOTTA("ORANGE_GLAZED_TERRACOTTA", 0, new String[]{"ORANGE_GLAZED_TERRACOTTA"}),
    ORANGE_SHULKER_BOX("ORANGE_SHULKER_BOX", 0, new String[]{"ORANGE_SHULKER_BOX"}),
    ORANGE_STAINED_GLASS("ORANGE_STAINED_GLASS", 1, new String[]{"STAINED_GLASS"}),
    ORANGE_STAINED_GLASS_PANE("ORANGE_STAINED_GLASS_PANE", 1, new String[]{"STAINED_GLASS_PANE"}),
    ORANGE_TERRACOTTA("ORANGE_TERRACOTTA", 1, new String[]{"STAINED_CLAY"}),
    ORANGE_TULIP("ORANGE_TULIP", 5, new String[]{"RED_ROSE"}),
    ORANGE_WALL_BANNER("ORANGE_WALL_BANNER", 0, new String[]{"WALL_BANNER"}),
    ORANGE_WOOL("ORANGE_WOOL", 1, new String[]{"WOOL"}),
    OXEYE_DAISY("OXEYE_DAISY", 8, new String[]{"RED_ROSE"}),
    PACKED_ICE("PACKED_ICE", 0, new String[]{"PACKED_ICE"}),
    PAINTING("PAINTING", 0, new String[]{"PAINTING"}),
    PAPER("PAPER", 0, new String[]{"PAPER"}),
    PARROT_SPAWN_EGG("PARROT_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    PEONY("PEONY", 5, new String[]{"DOUBLE_PLANT"}),
    PETRIFIED_OAK_SLAB("PETRIFIED_OAK_SLAB", 0, new String[]{"STONE"}),
    PHANTOM_MEMBRANE("PHANTOM_MEMBRANE", 0, new String[]{"STONE"}),
    PHANTOM_SPAWN_EGG("PHANTOM_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    PIG_SPAWN_EGG("PIG_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    PINK_BANNER("PINK_BANNER", 9, new String[]{"BANNER", "STANDING_BANNER"}),
    PINK_BED("PINK_BED", 6, new String[]{"BED", "BED_BLOCK"}),
    PINK_CARPET("PINK_CARPET", 6, new String[]{"CARPET"}),
    PINK_CONCRETE("PINK_CONCRETE", 6, new String[]{"CONCRETE"}),
    PINK_CONCRETE_POWDER("PINK_CONCRETE_POWDER", 6, new String[]{"CONCRETE_POWDER"}),
    PINK_DYE("PINK_DYE", 9, new String[]{"INK_SACK"}),
    PINK_GLAZED_TERRACOTTA("PINK_GLAZED_TERRACOTTA", 0, new String[]{"PINK_GLAZED_TERRACOTTA"}),
    PINK_SHULKER_BOX("PINK_SHULKER_BOX", 0, new String[]{"PINK_SHULKER_BOX"}),
    PINK_STAINED_GLASS("PINK_STAINED_GLASS", 6, new String[]{"STAINED_GLASS"}),
    PINK_STAINED_GLASS_PANE("PINK_STAINED_GLASS_PANE", 6, new String[]{"STAINED_GLASS_PANE"}),
    PINK_TERRACOTTA("PINK_TERRACOTTA", 6, new String[]{"STAINED_CLAY"}),
    PINK_TULIP("PINK_TULIP", 7, new String[]{"RED_ROSE"}),
    PINK_WALL_BANNER("PINK_WALL_BANNER", 0, new String[]{"WALL_BANNER"}),
    PINK_WOOL("PINK_WOOL", 6, new String[]{"WOOL"}),
    PISTON("PISTON", 0, new String[]{"PISTON_BASE"}),
    PISTON_HEAD("PISTON_HEAD", 0, new String[]{"PISTON_EXTENSION"}),
    PLAYER_HEAD("PLAYER_HEAD", 3, new String[]{"SKULL_ITEM", "SKULL"}),
    PLAYER_WALL_HEAD("PLAYER_WALL_HEAD", 0, new String[]{"SKULL", "SKULL_ITEM"}),
    PODZOL("PODZOL", 2, new String[]{"DIRT"}),
    POISONOUS_POTATO("POISONOUS_POTATO", 0, new String[]{"POISONOUS_POTATO"}),
    POLAR_BEAR_SPAWN_EGG("POLAR_BEAR_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    POLISHED_ANDESITE("POLISHED_ANDESITE", 6, new String[]{"STONE"}),
    POLISHED_DIORITE("POLISHED_DIORITE", 4, new String[]{"STONE"}),
    POLISHED_GRANITE("POLISHED_GRANITE", 2, new String[]{"STONE"}),
    POPPED_CHORUS_FRUIT("POPPED_CHORUS_FRUIT", 0, new String[]{"CHORUS_FRUIT_POPPED"}),
    POPPY("POPPY", 0, new String[]{"RED_ROSE"}),
    PORKCHOP("PORKCHOP", 0, new String[]{"PORK"}),
    POTATO("POTATO", 0, new String[]{"POTATO_ITEM"}),
    POTATOES("POTATOES", 0, new String[]{"POTATO"}),
    POTION("POTION", 0, new String[]{"POTION"}),
    POTTED_ACACIA_SAPLING("POTTED_ACACIA_SAPLING", 0, new String[]{"FLOWER_POT"}),
    POTTED_ALLIUM("POTTED_ALLIUM", 0, new String[]{"FLOWER_POT"}),
    POTTED_AZURE_BLUET("POTTED_AZURE_BLUET", 0, new String[]{"FLOWER_POT"}),
    POTTED_BIRCH_SAPLING("POTTED_BIRCH_SAPLING", 0, new String[]{"FLOWER_POT"}),
    POTTED_BLUE_ORCHID("POTTED_BLUE_ORCHID", 0, new String[]{"FLOWER_POT"}),
    POTTED_BROWN_MUSHROOM("POTTED_BROWN_MUSHROOM", 0, new String[]{"FLOWER_POT"}),
    POTTED_CACTUS("POTTED_CACTUS", 0, new String[]{"FLOWER_POT"}),
    POTTED_DANDELION("POTTED_DANDELION", 0, new String[]{"FLOWER_POT"}),
    POTTED_DARK_OAK_SAPLING("POTTED_DARK_OAK_SAPLING", 0, new String[]{"FLOWER_POT"}),
    POTTED_DEAD_BUSH("POTTED_DEAD_BUSH", 0, new String[]{"FLOWER_POT"}),
    POTTED_FERN("POTTED_FERN", 0, new String[]{"FLOWER_POT"}),
    POTTED_JUNGLE_SAPLING("POTTED_JUNGLE_SAPLING", 0, new String[]{"FLOWER_POT"}),
    POTTED_OAK_SAPLING("POTTED_OAK_SAPLING", 0, new String[]{"FLOWER_POT"}),
    POTTED_ORANGE_TULIP("POTTED_ORANGE_TULIP", 0, new String[]{"FLOWER_POT"}),
    POTTED_OXEYE_DAISY("POTTED_OXEYE_DAISY", 0, new String[]{"FLOWER_POT"}),
    POTTED_PINK_TULIP("POTTED_PINK_TULIP", 0, new String[]{"FLOWER_POT"}),
    POTTED_POPPY("POTTED_POPPY", 0, new String[]{"FLOWER_POT"}),
    POTTED_RED_MUSHROOM("POTTED_RED_MUSHROOM", 0, new String[]{"FLOWER_POT"}),
    POTTED_RED_TULIP("POTTED_RED_TULIP", 0, new String[]{"FLOWER_POT"}),
    POTTED_SPRUCE_SAPLING("POTTED_SPRUCE_SAPLING", 0, new String[]{"FLOWER_POT"}),
    POTTED_WHITE_TULIP("POTTED_WHITE_TULIP", 0, new String[]{"FLOWER_POT"}),
    POWERED_RAIL("POWERED_RAIL", 0, new String[]{"POWERED_RAIL"}),
    PRISMARINE("PRISMARINE", 0, new String[]{"PRISMARINE"}),
    PRISMARINE_BRICK_SLAB("PRISMARINE_BRICK_SLAB", 0, new String[]{"STONE"}),
    PRISMARINE_BRICK_STAIRS("PRISMARINE_BRICK_STAIRS", 0, new String[]{"STONE"}),
    PRISMARINE_BRICKS("PRISMARINE_BRICKS", 1, new String[]{"PRISMARINE"}),
    PRISMARINE_CRYSTALS("PRISMARINE_CRYSTALS", 0, new String[]{"PRISMARINE_CRYSTALS"}),
    PRISMARINE_SHARD("PRISMARINE_SHARD", 0, new String[]{"PRISMARINE_SHARD"}),
    PRISMARINE_SLAB("PRISMARINE_SLAB", 0, new String[]{"STONE"}),
    PRISMARINE_STAIRS("PRISMARINE_STAIRS", 0, new String[]{"STONE"}),
    PUFFERFISH("PUFFERFISH", 3, new String[]{"RAW_FISH"}),
    PUFFERFISH_BUCKET("PUFFERFISH_BUCKET", 0, new String[]{"STONE"}),
    PUFFERFISH_SPAWN_EGG("PUFFERFISH_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    PUMPKIN("PUMPKIN", 0, new String[]{"PUMPKIN"}),
    PUMPKIN_PIE("PUMPKIN_PIE", 0, new String[]{"PUMPKIN_PIE"}),
    PUMPKIN_SEEDS("PUMPKIN_SEEDS", 0, new String[]{"PUMPKIN_SEEDS"}),
    PUMPKIN_STEM("PUMPKIN_STEM", 0, new String[]{"PUMPKIN_STEM"}),
    PURPLE_BANNER("PURPLE_BANNER", 5, new String[]{"BANNER", "STANDING_BANNER"}),
    PURPLE_BED("PURPLE_BED", 10, new String[]{"BED", "BED_BLOCK"}),
    PURPLE_CARPET("PURPLE_CARPET", 10, new String[]{"CARPET"}),
    PURPLE_CONCRETE("PURPLE_CONCRETE", 10, new String[]{"CONCRETE"}),
    PURPLE_CONCRETE_POWDER("PURPLE_CONCRETE_POWDER", 10, new String[]{"CONCRETE_POWDER"}),
    PURPLE_DYE("PURPLE_DYE", 5, new String[]{"INK_SACK"}),
    PURPLE_GLAZED_TERRACOTTA("PURPLE_GLAZED_TERRACOTTA", 0, new String[]{"PURPLE_GLAZED_TERRACOTTA"}),
    PURPLE_SHULKER_BOX("PURPLE_SHULKER_BOX", 0, new String[]{"PURPLE_SHULKER_BOX"}),
    PURPLE_STAINED_GLASS("PURPLE_STAINED_GLASS", 10, new String[]{"STAINED_GLASS"}),
    PURPLE_STAINED_GLASS_PANE("PURPLE_STAINED_GLASS_PANE", 10, new String[]{"STAINED_GLASS_PANE"}),
    PURPLE_TERRACOTTA("PURPLE_TERRACOTTA", 10, new String[]{"STAINED_CLAY"}),
    PURPLE_WALL_BANNER("PURPLE_WALL_BANNER", 0, new String[]{"WALL_BANNER"}),
    PURPLE_WOOL("PURPLE_WOOL", 10, new String[]{"WOOL"}),
    PURPUR_BLOCK("PURPUR_BLOCK", 0, new String[]{"PURPUR_BLOCK"}),
    PURPUR_PILLAR("PURPUR_PILLAR", 0, new String[]{"PURPUR_PILLAR"}),
    PURPUR_SLAB("PURPUR_SLAB", 0, new String[]{"PURPUR_SLAB", "PURPUR_DOUBLE_SLAB"}),
    PURPUR_STAIRS("PURPUR_STAIRS", 0, new String[]{"PURPUR_STAIRS"}),
    QUARTZ("QUARTZ", 0, new String[]{"QUARTZ"}),
    QUARTZ_BLOCK("QUARTZ_BLOCK", 0, new String[]{"QUARTZ_BLOCK"}),
    QUARTZ_PILLAR("QUARTZ_PILLAR", 2, new String[]{"QUARTZ_BLOCK"}),
    QUARTZ_SLAB("QUARTZ_SLAB", 7, new String[]{"STEP"}),
    QUARTZ_STAIRS("QUARTZ_STAIRS", 0, new String[]{"QUARTZ_STAIRS"}),
    RABBIT("RABBIT", 0, new String[]{"RABBIT"}),
    RABBIT_FOOT("RABBIT_FOOT", 0, new String[]{"RABBIT_FOOT"}),
    RABBIT_HIDE("RABBIT_HIDE", 0, new String[]{"RABBIT_HIDE"}),
    RABBIT_SPAWN_EGG("RABBIT_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    RABBIT_STEW("RABBIT_STEW", 0, new String[]{"RABBIT_STEW"}),
    RAIL("RAIL", 0, new String[]{"RAILS"}),
    RED_BANNER("RED_BANNER", 1, new String[]{"BANNER", "STANDING_BANNER"}),
    RED_BED("RED_BED", 14, new String[]{"BED", "BED_BLOCK"}),
    RED_CARPET("RED_CARPET", 14, new String[]{"CARPET"}),
    RED_CONCRETE("RED_CONCRETE", 14, new String[]{"CONCRETE"}),
    RED_CONCRETE_POWDER("RED_CONCRETE_POWDER", 14, new String[]{"CONCRETE_POWDER"}),
    RED_DYE("RED_DYE", 1, new String[]{"INK_SACK", "ROSE_RED"}),
    RED_GLAZED_TERRACOTTA("RED_GLAZED_TERRACOTTA", 0, new String[]{"RED_GLAZED_TERRACOTTA"}),
    RED_MUSHROOM("RED_MUSHROOM", 0, new String[]{"RED_MUSHROOM"}),
    RED_MUSHROOM_BLOCK("RED_MUSHROOM_BLOCK", 0, new String[]{"RED_MUSHROOM", "HUGE_MUSHROOM_2"}),
    RED_NETHER_BRICKS("RED_NETHER_BRICKS", 0, new String[]{"RED_NETHER_BRICK"}),
    RED_SAND("RED_SAND", 1, new String[]{"SAND"}),
    RED_SANDSTONE("RED_SANDSTONE", 0, new String[]{"RED_SANDSTONE"}),
    RED_SANDSTONE_SLAB("RED_SANDSTONE_SLAB", 0, new String[]{"STONE_SLAB2", "DOUBLE_STONE_SLAB2"}),
    RED_SANDSTONE_STAIRS("RED_SANDSTONE_STAIRS", 0, new String[]{"RED_SANDSTONE_STAIRS"}),
    RED_SHULKER_BOX("RED_SHULKER_BOX", 0, new String[]{"RED_SHULKER_BOX"}),
    RED_STAINED_GLASS("RED_STAINED_GLASS", 14, new String[]{"STAINED_GLASS"}),
    RED_STAINED_GLASS_PANE("RED_STAINED_GLASS_PANE", 14, new String[]{"STAINED_GLASS_PANE"}),
    RED_TERRACOTTA("RED_TERRACOTTA", 14, new String[]{"STAINED_CLAY"}),
    RED_TULIP("RED_TULIP", 4, new String[]{"RED_ROSE"}),
    RED_WALL_BANNER("RED_WALL_BANNER", 0, new String[]{"WALL_BANNER"}),
    RED_WOOL("RED_WOOL", 14, new String[]{"WOOL"}),
    REDSTONE("REDSTONE", 0, new String[]{"REDSTONE"}),
    REDSTONE_BLOCK("REDSTONE_BLOCK", 0, new String[]{"REDSTONE_BLOCK"}),
    REDSTONE_LAMP("REDSTONE_LAMP", 0, new String[]{"REDSTONE_LAMP_ON", "REDSTONE_LAMP_OFF"}),
    REDSTONE_ORE("REDSTONE_ORE", 0, new String[]{"REDSTONE_ORE", "GLOWING_REDSTONE_ORE"}),
    REDSTONE_TORCH("REDSTONE_TORCH", 0, new String[]{"REDSTONE_TORCH_ON", "REDSTONE_TORCH_OFF"}),
    REDSTONE_WALL_TORCH("REDSTONE_WALL_TORCH", 1, new String[]{"REDSTONE_TORCH_ON", "REDSTONE_TORCH_OFF"}),
    REDSTONE_WIRE("REDSTONE_WIRE", 0, new String[]{"REDSTONE_WIRE"}),
    REPEATER("REPEATER", 0, new String[]{"DIODE", "DIODE_BLOCK_ON", "DIODE_BLOCK_OFF"}),
    REPEATING_COMMAND_BLOCK("REPEATING_COMMAND_BLOCK", 0, new String[]{"COMMAND_REPEATING"}),
    ROSE_BUSH("ROSE_BUSH", 4, new String[]{"DOUBLE_PLANT"}),
    ROSE_RED("ROSE_RED", 1, new String[]{"INK_SACK", "RED_DYE"}),
    ROTTEN_FLESH("ROTTEN_FLESH", 0, new String[]{"ROTTEN_FLESH"}),
    SADDLE("SADDLE", 0, new String[]{"SADDLE"}),
    SALMON("SALMON", 1, new String[]{"RAW_FISH"}),
    SALMON_BUCKET("SALMON_BUCKET", 0, new String[]{"BUCKET"}),
    SALMON_SPAWN_EGG("SALMON_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    SAND("SAND", 0, new String[]{"SAND"}),
    SANDSTONE("SANDSTONE", 0, new String[]{"SANDSTONE"}),
    SANDSTONE_SLAB("SANDSTONE_SLAB", 1, new String[]{"STONE_SLAB", "STEP", "DOUBLE_STEP"}),
    SANDSTONE_STAIRS("SANDSTONE_STAIRS", 0, new String[]{"SANDSTONE_STAIRS"}),
    SCUTE("SCUTE", 0, new String[]{"STONE"}),
    SEA_LANTERN("SEA_LANTERN", 0, new String[]{"SEA_LANTERN"}),
    SEA_PICKLE("SEA_PICKLE", 0, new String[]{"STONE"}),
    SEAGRASS("SEAGRASS", 0, new String[]{"STONE"}),
    SHEARS("SHEARS", 0, new String[]{"SHEARS"}),
    SHEEP_SPAWN_EGG("SHEEP_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    SHIELD("SHIELD", 0, new String[]{"SHIELD"}),
    SHULKER_BOX("SHULKER_BOX", 0, new String[]{"PURPLE_SHULKER_BOX"}),
    SHULKER_SHELL("SHULKER_SHELL", 0, new String[]{"SHULKER_SHELL"}),
    SHULKER_SPAWN_EGG("SHULKER_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    SIGN("SIGN", 0, new String[]{"OAK_SIGN", "SIGN"}),
    SILVERFISH_SPAWN_EGG("SILVERFISH_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    SKELETON_HORSE_SPAWN_EGG("SKELETON_HORSE_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    SKELETON_SKULL("SKELETON_SKULL", 0, new String[]{"SKULL_ITEM", "SKULL"}),
    SKELETON_SKULL_17("SKELETON_SKULL", 0, new String[]{"SKULL_ITEM", "SKULL"}),
    SKELETON_SPAWN_EGG("SKELETON_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    SKELETON_WALL_SKULL("SKELETON_WALL_SKULL", 0, new String[]{"SKULL", "SKULL_ITEM"}),
    SLIME_BALL("SLIME_BALL", 0, new String[]{"SLIME_BALL"}),
    SLIME_BLOCK("SLIME_BLOCK", 0, new String[]{"SLIME_BLOCK"}),
    SLIME_SPAWN_EGG("SLIME_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    SMOOTH_QUARTZ("SMOOTH_QUARTZ", 0, new String[]{"STONE"}),
    SMOOTH_RED_SANDSTONE("SMOOTH_RED_SANDSTONE", 2, new String[]{"RED_SANDSTONE"}),
    SMOOTH_SANDSTONE("SMOOTH_SANDSTONE", 2, new String[]{"SANDSTONE"}),
    SMOOTH_STONE("SMOOTH_STONE", 0, new String[]{"STEP"}),
    SNOW("SNOW", 0, new String[]{"SNOW"}),
    SNOW_BLOCK("SNOW_BLOCK", 0, new String[]{"SNOW_BLOCK"}),
    SNOWBALL("SNOWBALL", 0, new String[]{"SNOW_BALL"}),
    SOUL_SAND("SOUL_SAND", 0, new String[]{"SOUL_SAND"}),
    SPAWNER("SPAWNER", 0, new String[]{"MOB_SPAWNER"}),
    SPECTRAL_ARROW("SPECTRAL_ARROW", 0, new String[]{"SPECTRAL_ARROW"}),
    SPIDER_EYE("SPIDER_EYE", 0, new String[]{"SPIDER_EYE"}),
    SPIDER_SPAWN_EGG("SPIDER_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    SPLASH_POTION("SPLASH_POTION", 0, new String[]{"SPLASH_POTION"}),
    SPONGE("SPONGE", 0, new String[]{"SPONGE"}),
    SPRUCE_BOAT("SPRUCE_BOAT", 0, new String[]{"BOAT_SPRUCE"}),
    SPRUCE_BUTTON("SPRUCE_BUTTON", 0, new String[]{"WOOD_BUTTON"}),
    SPRUCE_DOOR("SPRUCE_DOOR", 0, new String[]{"SPRUCE_DOOR", "SPRUCE_DOOR_ITEM"}),
    SPRUCE_FENCE("SPRUCE_FENCE", 0, new String[]{"SPRUCE_FENCE"}),
    SPRUCE_FENCE_GATE("SPRUCE_FENCE_GATE", 0, new String[]{"SPRUCE_FENCE_GATE"}),
    SPRUCE_LEAVES("SPRUCE_LEAVES", 1, new String[]{"LEAVES"}),
    SPRUCE_LOG("SPRUCE_LOG", 1, new String[]{"LOG"}),
    SPRUCE_PLANKS("SPRUCE_PLANKS", 1, new String[]{"WOOD"}),
    SPRUCE_PRESSURE_PLATE("SPRUCE_PRESSURE_PLATE", 0, new String[]{"WOOD_PLATE"}),
    SPRUCE_SAPLING("SPRUCE_SAPLING", 1, new String[]{"SAPLING"}),
    SPRUCE_SLAB("SPRUCE_SLAB", 1, new String[]{"WOODEN_SLAB", "WOOD_STEP", "WOOD_DOUBLE_STEP"}),
    SPRUCE_STAIRS("SPRUCE_STAIRS", 0, new String[]{"SPRUCE_WOOD_STAIRS"}),
    SPRUCE_TRAPDOOR("SPRUCE_TRAPDOOR", 0, new String[]{"TRAP_DOOR"}),
    SPRUCE_WOOD("SPRUCE_WOOD", 1, new String[]{"LOG"}),
    SQUID_SPAWN_EGG("SQUID_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    STICK("STICK", 0, new String[]{"STICK"}),
    STICKY_PISTON("STICKY_PISTON", 0, new String[]{"PISTON_STICKY_BASE"}),
    STONE("STONE", 0, new String[]{"STONE"}),
    STONE_AXE("STONE_AXE", 0, new String[]{"STONE_AXE"}),
    STONE_BRICK_SLAB("STONE_BRICK_SLAB", 5, new String[]{"STONE_SLAB", "STEP", "DOUBLE_STEP"}),
    STONE_BRICK_STAIRS("STONE_BRICK_STAIRS", 0, new String[]{"SMOOTH_STAIRS"}),
    STONE_BRICKS("STONE_BRICKS", 0, new String[]{"SMOOTH_BRICK"}),
    STONE_BUTTON("STONE_BUTTON", 0, new String[]{"STONE_BUTTON"}),
    STONE_HOE("STONE_HOE", 0, new String[]{"STONE_HOE"}),
    STONE_PICKAXE("STONE_PICKAXE", 0, new String[]{"STONE_PICKAXE"}),
    STONE_PRESSURE_PLATE("STONE_PRESSURE_PLATE", 0, new String[]{"STONE_PLATE"}),
    STONE_SHOVEL("STONE_SHOVEL", 0, new String[]{"STONE_SPADE"}),
    STONE_SLAB("STONE_SLAB", 0, new String[]{"STONE_SLAB", "STEP", "DOUBLE_STEP"}),
    STONE_SWORD("STONE_SWORD", 0, new String[]{"STONE_SWORD"}),
    STRAY_SPAWN_EGG("STRAY_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    STRING("STRING", 0, new String[]{"STRING"}),
    STRIPPED_ACACIA_LOG("STRIPPED_ACACIA_LOG", 0, new String[]{"STONE"}),
    STRIPPED_ACACIA_WOOD("STRIPPED_ACACIA_WOOD", 0, new String[]{"STONE"}),
    STRIPPED_BIRCH_LOG("STRIPPED_BIRCH_LOG", 0, new String[]{"STONE"}),
    STRIPPED_BIRCH_WOOD("STRIPPED_BIRCH_WOOD", 0, new String[]{"STONE"}),
    STRIPPED_DARK_OAK_LOG("STRIPPED_DARK_OAK_LOG", 0, new String[]{"STONE"}),
    STRIPPED_DARK_OAK_WOOD("STRIPPED_DARK_OAK_WOOD", 0, new String[]{"STONE"}),
    STRIPPED_JUNGLE_LOG("STRIPPED_JUNGLE_LOG", 0, new String[]{"STONE"}),
    STRIPPED_JUNGLE_WOOD("STRIPPED_JUNGLE_WOOD", 0, new String[]{"STONE"}),
    STRIPPED_OAK_LOG("STRIPPED_OAK_LOG", 0, new String[]{"STONE"}),
    STRIPPED_OAK_WOOD("STRIPPED_OAK_WOOD", 0, new String[]{"STONE"}),
    STRIPPED_SPRUCE_LOG("STRIPPED_SPRUCE_LOG", 0, new String[]{"STONE"}),
    STRIPPED_SPRUCE_WOOD("STRIPPED_SPRUCE_WOOD", 0, new String[]{"STONE"}),
    STRUCTURE_BLOCK("STRUCTURE_BLOCK", 0, new String[]{"STRUCTURE_BLOCK"}),
    STRUCTURE_VOID("STRUCTURE_VOID", 0, new String[]{"STRUCTURE_VOID"}),
    SUGAR("SUGAR", 0, new String[]{"SUGAR"}),
    SUGAR_CANE("SUGAR_CANE", 0, new String[]{"SUGAR_CANE", "SUGAR_CANE_BLOCK"}),
    SUNFLOWER("SUNFLOWER", 0, new String[]{"DOUBLE_PLANT"}),
    TALL_GRASS("TALL_GRASS", 2, new String[]{"DOUBLE_PLANT"}),
    TALL_SEAGRASS("TALL_SEAGRASS", 0, new String[]{"STONE"}),
    TERRACOTTA("TERRACOTTA", 0, new String[]{"HARD_CLAY"}),
    TIPPED_ARROW("TIPPED_ARROW", 0, new String[]{"TIPPED_ARROW"}),
    TNT("TNT", 0, new String[]{"TNT"}),
    TNT_MINECART("TNT_MINECART", 0, new String[]{"EXPLOSIVE_MINECART"}),
    TORCH("TORCH", 0, new String[]{"TORCH"}),
    TOTEM_OF_UNDYING("TOTEM_OF_UNDYING", 0, new String[]{"TOTEM"}),
    TRAPPED_CHEST("TRAPPED_CHEST", 0, new String[]{"TRAPPED_CHEST"}),
    TRIDENT("TRIDENT", 0, new String[]{"STONE"}),
    TRIPWIRE("TRIPWIRE", 0, new String[]{"TRIPWIRE"}),
    TRIPWIRE_HOOK("TRIPWIRE_HOOK", 0, new String[]{"TRIPWIRE_HOOK"}),
    TROPICAL_FISH("TROPICAL_FISH", 0, new String[]{"RAW_FISH"}),
    TROPICAL_FISH_BUCKET("TROPICAL_FISH_BUCKET", 0, new String[]{"BUCKET"}),
    TROPICAL_FISH_SPAWN_EGG("TROPICAL_FISH_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    TUBE_CORAL("TUBE_CORAL", 0, new String[]{"STONE"}),
    TUBE_CORAL_BLOCK("TUBE_CORAL_BLOCK", 0, new String[]{"STONE"}),
    TUBE_CORAL_FAN("TUBE_CORAL_FAN", 0, new String[]{"STONE"}),
    TURTLE_EGG("TURTLE_EGG", 0, new String[]{"MONSTER_EGG"}),
    TURTLE_HELMET("TURTLE_HELMET", 0, new String[]{"STONE"}),
    TURTLE_SPAWN_EGG("TURTLE_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    VEX_SPAWN_EGG("VEX_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    VILLAGER_SPAWN_EGG("VILLAGER_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    VINDICATOR_SPAWN_EGG("VINDICATOR_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    VINE("VINE", 0, new String[]{"VINE"}),
    VOID_AIR("VOID_AIR", 0, new String[]{"AIR"}),
    WALL_SIGN("WALL_SIGN", 0, new String[]{"WALL_SIGN", "SIGN_POST"}),
    WALL_SIGN_N("WALL_SIGN", 1, new String[]{"WALL_SIGN", "SIGN_POST"}),
    WALL_SIGN_O("WALL_SIGN", 4, new String[]{"WALL_SIGN", "SIGN_POST"}),
    WALL_SIGN_S("WALL_SIGN", 3, new String[]{"WALL_SIGN", "SIGN_POST"}),
    WALL_SIGN_W("WALL_SIGN", 2, new String[]{"WALL_SIGN", "SIGN_POST"}),
    WALL_TORCH("WALL_TORCH", 1, new String[]{"TORCH"}),
    WATER("WATER", 0, new String[]{"WATER", "STATIONARY_WATER"}),
    WATER_BUCKET("WATER_BUCKET", 0, new String[]{"WATER_BUCKET"}),
    WET_SPONGE("WET_SPONGE", 1, new String[]{"SPONGE"}),
    WHEAT("WHEAT", 0, new String[]{"WHEAT", "CROPS"}),
    WHEAT_SEEDS("WHEAT_SEEDS", 0, new String[]{"WHEAT_SEEDS", "SEEDS"}),
    WHITE_BANNER("WHITE_BANNER", 15, new String[]{"BANNER", "STANDING_BANNER"}),
    WHITE_BED("WHITE_BED", 0, new String[]{"BED", "BED_BLOCK"}),
    WHITE_CARPET("WHITE_CARPET", 0, new String[]{"CARPET"}),
    WHITE_CONCRETE("WHITE_CONCRETE", 0, new String[]{"CONCRETE"}),
    WHITE_CONCRETE_POWDER("WHITE_CONCRETE_POWDER", 0, new String[]{"CONCRETE_POWDER"}),
    WHITE_DYE("WHITE_DYE", 15, new String[]{"INK_SACK"}),
    WHITE_GLAZED_TERRACOTTA("WHITE_GLAZED_TERRACOTTA", 0, new String[]{"WHITE_GLAZED_TERRACOTTA"}),
    WHITE_SHULKER_BOX("WHITE_SHULKER_BOX", 0, new String[]{"WHITE_SHULKER_BOX"}),
    WHITE_STAINED_GLASS("WHITE_STAINED_GLASS", 0, new String[]{"STAINED_GLASS"}),
    WHITE_STAINED_GLASS_PANE("WHITE_STAINED_GLASS_PANE", 0, new String[]{"STAINED_GLASS_PANE"}),
    WHITE_TERRACOTTA("WHITE_TERRACOTTA", 0, new String[]{"TERRACOTTA"}),
    WHITE_TULIP("WHITE_TULIP", 6, new String[]{"RED_ROSE"}),
    WHITE_WALL_BANNER("WHITE_WALL_BANNER", 0, new String[]{"WALL_BANNER"}),
    WHITE_WOOL("WHITE_WOOL", 0, new String[]{"WOOL"}),
    WITCH_SPAWN_EGG("WITCH_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    WITHER_SKELETON_SKULL("WITHER_SKELETON_SKULL", 0, new String[]{"SKULL", "SKULL_ITEM"}),
    WITHER_SKELETON_SPAWN_EGG("WITHER_SKELETON_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    WITHER_SKELETON_WALL_SKULL("WITHER_SKELETON_WALL_SKULL", 0, new String[]{"SKULL", "SKULL_ITEM"}),
    WOLF_SPAWN_EGG("WOLF_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    WOODEN_AXE("WOODEN_AXE", 0, new String[]{"WOOD_AXE"}),
    WOODEN_HOE("WOODEN_HOE", 0, new String[]{"WOOD_HOE"}),
    WOODEN_PICKAXE("WOODEN_PICKAXE", 0, new String[]{"WOOD_PICKAXE"}),
    WOODEN_SHOVEL("WOODEN_SHOVEL", 0, new String[]{"WOOD_SPADE"}),
    WOODEN_SWORD("WOODEN_SWORD", 0, new String[]{"WOOD_SWORD"}),
    WRITABLE_BOOK("WRITABLE_BOOK", 0, new String[]{"BOOK_AND_QUILL"}),
    WRITTEN_BOOK("WRITTEN_BOOK", 0, new String[]{"WRITTEN_BOOK"}),
    YELLOW_BANNER("YELLOW_BANNER", 11, new String[]{"BANNER", "STANDING_BANNER"}),
    YELLOW_BED("YELLOW_BED", 4, new String[]{"BED", "BED_BLOCK"}),
    YELLOW_CARPET("YELLOW_CARPET", 4, new String[]{"CARPET"}),
    YELLOW_CONCRETE("YELLOW_CONCRETE", 4, new String[]{"CONCRETE"}),
    YELLOW_CONCRETE_POWDER("YELLOW_CONCRETE_POWDER", 4, new String[]{"CONCRETE_POWDER"}),
    YELLOW_DYE("YELLOW_DYE", 11, new String[]{"INK_SACK", "DANDELION_YELLOW"}),
    YELLOW_GLAZED_TERRACOTTA("YELLOW_GLAZED_TERRACOTTA", 0, new String[]{"YELLOW_GLAZED_TERRACOTTA"}),
    YELLOW_SHULKER_BOX("YELLOW_SHULKER_BOX", 0, new String[]{"YELLOW_SHULKER_BOX"}),
    YELLOW_STAINED_GLASS("YELLOW_STAINED_GLASS", 4, new String[]{"STAINED_GLASS"}),
    YELLOW_STAINED_GLASS_PANE("YELLOW_STAINED_GLASS_PANE", 4, new String[]{"STAINED_GLASS_PANE"}),
    YELLOW_TERRACOTTA("YELLOW_TERRACOTTA", 4, new String[]{"STAINED_CLAY"}),
    YELLOW_WALL_BANNER("YELLOW_WALL_BANNER", 0, new String[]{"WALL_BANNER"}),
    YELLOW_WOOL("YELLOW_WOOL", 4, new String[]{"WOOL"}),
    ZOMBIE_HEAD("ZOMBIE_HEAD", 0, new String[]{"SKULL", "SKULL_ITEM"}),
    ZOMBIE_HORSE_SPAWN_EGG("ZOMBIE_HORSE_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    ZOMBIE_PIGMAN_SPAWN_EGG("ZOMBIE_PIGMAN_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    ZOMBIE_SPAWN_EGG("ZOMBIE_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    ZOMBIE_VILLAGER_SPAWN_EGG("ZOMBIE_VILLAGER_SPAWN_EGG", 0, new String[]{"MONSTER_EGG"}),
    ZOMBIE_WALL_HEAD("ZOMBIE_WALL_HEAD", 0, new String[]{"SKULL", "SKULL_ITEM"});

    private static HashMap<String, Materials> cachedSearch = new HashMap();
    private int data;
    private String[] matches;
    private String name;
    private Material parsed;

    private Materials(String name, int data, String... m) {
        this.name = name;
        this.matches = m;
        this.data = data;
    }

    public Materials fromMaterial(Material mat) {
        try {
            return valueOf(mat.toString());
        } catch (IllegalArgumentException var11) {
            Materials[] var3 = values();
            int var4 = var3.length;

            for(int var5 = 0; var5 < var4; ++var5) {
                Materials xmat = var3[var5];
                String[] var7 = xmat.matches;
                int var8 = var7.length;

                for(int var9 = 0; var9 < var8; ++var9) {
                    String test = var7[var9];
                    if (test.equalsIgnoreCase(mat.toString())) {
                        return xmat;
                    }
                }
            }

            return null;
        }
    }

    public int getData() {
        return this.data;
    }

    public String getName() {
        return this.name;
    }

    public boolean isDamageable(Materials type) {
        if (type == null) {
            return false;
        } else {
            String[] split = type.toString().split("_");
            int length = split.length;
            String var4 = split[length - 1];
            byte var5 = -1;
            switch(var4.hashCode()) {
                case -1850133582:
                    if (var4.equals("SHEARS")) {
                        var5 = 13;
                    }
                    break;
                case -1849815901:
                    if (var4.equals("SHOVEL")) {
                        var5 = 7;
                    }
                    break;
                case -1776664470:
                    if (var4.equals("LEGGINGS")) {
                        var5 = 2;
                    }
                    break;
                case -829199152:
                    if (var4.equals("TURTLE_HELMET")) {
                        var5 = 10;
                    }
                    break;
                case -342000110:
                    if (var4.equals("TRIDENT")) {
                        var5 = 11;
                    }
                    break;
                case 65262:
                    if (var4.equals("AXE")) {
                        var5 = 5;
                    }
                    break;
                case 71710:
                    if (var4.equals("HOE")) {
                        var5 = 8;
                    }
                    break;
                case 63384481:
                    if (var4.equals("BOOTS")) {
                        var5 = 3;
                    }
                    break;
                case 79322589:
                    if (var4.equals("SWORD")) {
                        var5 = 4;
                    }
                    break;
                case 139953965:
                    if (var4.equals("PICKAXE")) {
                        var5 = 6;
                    }
                    break;
                case 1456344605:
                    if (var4.equals("HORSE_ARMOR")) {
                        var5 = 12;
                    }
                    break;
                case 1555044533:
                    if (var4.equals("CHESTPLATE")) {
                        var5 = 1;
                    }
                    break;
                case 2048333745:
                    if (var4.equals("ELYTRA")) {
                        var5 = 9;
                    }
                    break;
                case 2127362157:
                    if (var4.equals("HELMET")) {
                        var5 = 0;
                    }
            }

            switch(var5) {
                case 0:
                    return true;
                case 1:
                    return true;
                case 2:
                    return true;
                case 3:
                    return true;
                case 4:
                    return true;
                case 5:
                    return true;
                case 6:
                    return true;
                case 7:
                    return true;
                case 8:
                    return true;
                case 9:
                    return true;
                case 10:
                    return true;
                case 11:
                    return true;
                case 12:
                    return true;
                case 13:
                    return true;
                default:
                    return false;
            }
        }
    }

    public boolean isSameMaterial(ItemStack comp) {
        if (isNewVersion()) {
            return comp.getType() == this.parseMaterial();
        } else if (comp.getType() == this.parseMaterial() && comp.getData().getData() == this.data) {
            return true;
        } else {
            Materials xmat = this.fromMaterial(comp.getType());
            return this.isDamageable(xmat) && this.parseMaterial() == comp.getType();
        }
    }

    public ItemStack parseItem() {
        Material mat = this.parseMaterial();
        return isNewVersion() ? new ItemStack(mat) : new ItemStack(mat, 1, (short)((byte)this.data));
    }

    public Material parseMaterial() {
        if (this.parsed != null) {
            return this.parsed;
        } else {
            Material mat = Material.matchMaterial(this.getName());
            if (mat != null && isNewVersion()) {
                return this.parsed = mat;
            } else {
                String[] var2 = this.matches;
                int var3 = var2.length;

                for(int var4 = 0; var4 < var3; ++var4) {
                    String m = var2[var4];
                    Material found = Material.matchMaterial(m);
                    if (found != null) {
                        return this.parsed = found;
                    }
                }

                throw new Error("Unable to find material: " + this.getName() + " " + Arrays.asList(this.matches));
            }
        }
    }

    public static Materials fromString(String key) {
        Materials xmat = null;
        String[] split = key.split(":");
        if (split.length == 1) {
            xmat = requestMaterial(key, (byte)0);
        } else {
            xmat = requestMaterial(split[0], (byte)Integer.parseInt(split[1]));
        }

        return xmat;
    }

    public static boolean isNewVersion() {
        Material mat = Material.getMaterial("RED_WOOL");
        return mat != null;
    }

    public static Materials requestMaterial(String name, byte data) {
        if (cachedSearch.containsKey(name.toUpperCase() + "," + data)) {
            return (Materials)cachedSearch.get(name.toUpperCase() + "," + data);
        } else {
            Materials[] var2 = values();
            int var3 = var2.length;

            for(int var4 = 0; var4 < var3; ++var4) {
                Materials mat = var2[var4];
                if (mat.getName().equals(name) && data == 0) {
                    cachedSearch.put(mat.getName() + "," + 0, mat);
                    return mat;
                }

                String[] var6 = mat.matches;
                int var7 = var6.length;

                for(int var8 = 0; var8 < var7; ++var8) {
                    String test = var6[var8];
                    if (name.toUpperCase().equals(test) && (byte)mat.data == data) {
                        cachedSearch.put(test + "," + data, mat);
                        return mat;
                    }
                }
            }

            return null;
        }
    }
}
